# Generated by Django 5.2.17 on 2026-08-15 08:44

import apps.assets.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_add_airun_canceled_status'),
        ('assets', '0001_initial'),
        ('catalog', '0003_remove_product_concepts'),
        ('identity', '0010_phaseae2eownership'),
        ('jobs', '0002_alter_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvidenceFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('PRODUCT', 'Product'), ('SPECIFICATION', 'Specification'), ('PROCESS', 'Process'), ('APPLICATION', 'Application'), ('STANDARD', 'Standard'), ('ADVANTAGE', 'Advantage')], max_length=24)),
                ('field_name', models.CharField(max_length=64)),
                ('value', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('source_page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_region', models.JSONField(blank=True, null=True, validators=[apps.assets.models.validate_source_region])),
                ('source_excerpt', models.TextField(max_length=2000)),
                ('risk_level', models.CharField(choices=[('STANDARD', 'Standard'), ('HIGH', 'High')], default='STANDARD', max_length=16)),
                ('review_status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=16)),
                ('provider_label', models.CharField(max_length=128)),
                ('is_demo', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, max_length=1000)),
                ('ai_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_evidence_facts', to='ai.airun')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_facts', to='assets.materialasset')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_evidence_facts', to='jobs.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_facts', to='catalog.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_product_evidence_facts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source_page', 'created_at', 'id'],
                'indexes': [models.Index(fields=['organization', 'product', 'review_status'], name='assets_fact_org_prod_rev_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'field_name', 'source_page', 'source_excerpt'), name='assets_unique_fact_per_job_source')],
            },
        ),
    ]
