# Generated by Django 5.2.17 on 2026-08-09 06:23

import apps.campaigns.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('catalog', '0003_remove_product_concepts'),
        ('identity', '0004_refresh_asset_permissions'),
        ('knowledge', '0002_knowledgegraphlock'),
        ('platforms', '0003_alter_connectorcredential_granted_scopes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='CampaignProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_links', to='campaigns.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_links', to='catalog.product')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ContentBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready')], default='DRAFT', max_length=16)),
                ('target_country', models.CharField(blank=True, max_length=128)),
                ('customer_type', models.CharField(blank=True, max_length=255)),
                ('content_objective', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=512)),
                ('landing_page_url', models.URLField(blank=True, max_length=2048)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('prohibited_claims', models.JSONField(blank=True, default=list, validators=[apps.campaigns.models.validate_text_list])),
                ('selling_points', models.JSONField(blank=True, default=list, validators=[apps.campaigns.models.validate_text_list])),
                ('advantages', models.JSONField(blank=True, default=list, validators=[apps.campaigns.models.validate_text_list])),
                ('keywords', models.JSONField(blank=True, default=list, validators=[apps.campaigns.models.validate_text_list])),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='briefs', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_content_briefs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='campaigns.contentbrief')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_content_briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ContentBriefAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_brief_links', to='assets.materialasset')),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_links', to='campaigns.contentbrief')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ContentBriefConceptLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('TARGET_INDUSTRY', 'Target industry'), ('TARGET_CUSTOMER_TYPE', 'Target customer type'), ('PURCHASE_INTENT', 'Purchase intent'), ('STANDARD', 'Standard'), ('APPLICATION', 'Application')], max_length=32)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concept_links', to='campaigns.contentbrief')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_brief_links', to='knowledge.knowledgeconcept')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ContentBriefPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_links', to='campaigns.contentbrief')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_brief_links', to='platforms.platform')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ContentBriefProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_links', to='campaigns.contentbrief')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_brief_links', to='catalog.product')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='campaigns_campaign_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='campaignproduct',
            constraint=models.UniqueConstraint(fields=('campaign', 'product'), name='campaigns_unique_campaign_product'),
        ),
        migrations.AddConstraint(
            model_name='contentbrief',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='campaigns_brief_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='contentbrief',
            constraint=models.UniqueConstraint(condition=models.Q(('previous_version__isnull', False)), fields=('previous_version',), name='campaigns_one_direct_revision'),
        ),
        migrations.AddConstraint(
            model_name='contentbriefasset',
            constraint=models.UniqueConstraint(fields=('brief', 'asset'), name='campaigns_unique_brief_asset'),
        ),
        migrations.AddConstraint(
            model_name='contentbriefconceptlink',
            constraint=models.UniqueConstraint(fields=('brief', 'role', 'concept'), name='campaigns_unique_brief_role_concept'),
        ),
        migrations.AddConstraint(
            model_name='contentbriefplatform',
            constraint=models.UniqueConstraint(fields=('brief', 'platform'), name='campaigns_unique_brief_platform'),
        ),
        migrations.AddConstraint(
            model_name='contentbriefproduct',
            constraint=models.UniqueConstraint(fields=('brief', 'product'), name='campaigns_unique_brief_product'),
        ),
    ]
