# Generated by Django 5.2.17 on 2026-08-15 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_brief_product_process_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentbrief',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentbrief',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_content_briefs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentbrief',
            name='archived_from_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='contentbrief',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16),
        ),
    ]
