# Generated by Django 5.2.17 on 2026-08-09 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('catalog', '0003_remove_product_concepts'),
        ('identity', '0008_refresh_publishing_permissions'),
        ('platforms', '0004_socialaccount_connector_metadata_and_more'),
        ('publishing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.URLField(max_length=2048)),
                ('full_url', models.URLField(max_length=2048)),
                ('utm_source', models.CharField(max_length=128)),
                ('utm_medium', models.CharField(max_length=128)),
                ('utm_campaign', models.CharField(max_length=128)),
                ('utm_content', models.CharField(blank=True, max_length=128)),
                ('utm_term', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_links', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_tracking_links', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_links', to='platforms.platform')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_links', to='catalog.product')),
                ('published_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_links', to='publishing.publishedpost')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=16)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_short_links', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('tracking_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_links', to='tracking.trackinglink')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('occurred_date', models.DateField()),
                ('country', models.CharField(blank=True, max_length=2)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('other', 'Other')], max_length=16)),
                ('referrer_host', models.CharField(blank=True, max_length=253)),
                ('network_hash', models.CharField(max_length=64)),
                ('hash_version', models.CharField(max_length=32)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='click_events', to='campaigns.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='click_events', to='platforms.platform')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='click_events', to='catalog.product')),
                ('short_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='click_events', to='tracking.shortlink')),
                ('tracking_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='click_events', to='tracking.trackinglink')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='trackinglink',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='tracking_unique_tracking_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='shortlink',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='tracking_unique_short_idempotency'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['organization', 'occurred_date'], name='tracking_click_org_date'),
        ),
    ]
