# Generated by Django 5.2.17 on 2026-08-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='publishing_fingerprint',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='short_fingerprint',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='short_code_snapshot',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='tracking_fingerprint',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
