# Generated by Django 5.2.17 on 2026-08-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_clickevent_publishing_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='content_provenance_snapshot',
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='master_content_provenance_snapshot',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
