# Generated by Django 5.2.17 on 2026-08-17 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
        ('tracking', '0003_clickevent_content_provenance_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinglink',
            name='published_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_links', to='publishing.publishedpost'),
        ),
    ]
