# Generated by Django 5.2.17 on 2026-08-09 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('identity', '0007_refresh_content_permissions'),
        ('platforms', '0004_socialaccount_connector_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('claim_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('STALE', 'Stale')], max_length=16)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('outcome', models.CharField(blank=True, max_length=32)),
                ('error', models.JSONField(blank=True, null=True)),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['task_id', 'number'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PublishTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_version', models.PositiveIntegerField()),
                ('connector_code', models.CharField(default='mock', max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('requested_timezone', models.CharField(default='UTC', max_length=64)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('attempt_number', models.PositiveIntegerField(default=0)),
                ('retry_not_before', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_publish_tasks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publish_tasks', to='platforms.platform')),
                ('platform_content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publish_tasks', to='content.platformcontent')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publish_tasks', to='platforms.socialaccount')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PublishedPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='published_post', to='publishing.publishattempt')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('platform_content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_posts', to='content.platformcontent')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_posts', to='platforms.socialaccount')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='published_post', to='publishing.publishtask')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='publishattempt',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='publishing.publishtask'),
        ),
        migrations.AddConstraint(
            model_name='publishtask',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='publishing_unique_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='publishattempt',
            constraint=models.UniqueConstraint(fields=('task', 'number'), name='publishing_unique_attempt_number'),
        ),
    ]
