# Generated by Django 5.2.17 on 2026-08-17 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_organization_ai_daily_token_budget'),
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_on', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='demo', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='publishing.publishedpost')),
            ],
            options={
                'ordering': ['-collected_on', '-id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('post', 'collected_on'), name='publishing_unique_post_metric_day')],
            },
        ),
    ]
