# Generated by Django 5.2.17 on 2026-08-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_postmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishtask',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishtask',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
