# Generated by Django 5.2.17 on 2026-08-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0003_publishtask_heartbeat_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishattempt',
            name='provider_submission_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='publishtask',
            name='provider_submission_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publishattempt',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('SUBMITTED', 'Submitted'), ('SUBMISSION_UNKNOWN', 'Submission unknown'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('STALE', 'Stale')], max_length=32),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUBMITTED', 'Submitted'), ('SUBMISSION_UNKNOWN', 'Submission unknown'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], max_length=32),
        ),
    ]
