# Generated by Django 5.2.17 on 2026-08-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0004_publishattempt_provider_submission_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishattempt',
            name='provider_call_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishtask',
            name='provider_call_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
