# Generated by Django 5.2.7 on 2026-08-20

from django.db import migrations, models
from django.db.models import Count


LIVE_STATUSES = (
    "SCHEDULED",
    "QUEUED",
    "RUNNING",
    "SUBMITTED",
    "SUBMISSION_UNKNOWN",
    "SUCCEEDED",
)
GROUP_FIELDS = (
    "organization_id",
    "platform_content_id",
    "content_version",
    "social_account_id",
)


def precheck_duplicate_live_tasks(apps, schema_editor):
    PublishTask = apps.get_model("publishing", "PublishTask")
    live_tasks = PublishTask.objects.using(schema_editor.connection.alias).filter(
        status__in=LIVE_STATUSES
    )
    duplicate_keys = (
        live_tasks.values(*GROUP_FIELDS)
        .annotate(task_count=Count("id"))
        .filter(task_count__gt=1)
        .order_by(*GROUP_FIELDS)
    )
    groups = []
    for key in duplicate_keys:
        filters = {field: key[field] for field in GROUP_FIELDS}
        tasks = list(
            live_tasks.filter(**filters).order_by("id").values("id", "status")
        )
        groups.append(
            ", ".join(
                f"task_id={task['id']} status={task['status']}" for task in tasks
            )
        )
    if groups:
        details = "; ".join(
            f"Group {index}: {group}" for index, group in enumerate(groups, start=1)
        )
        raise RuntimeError(
            "Publishing migration 0006 cannot add the live-task uniqueness "
            f"constraint because duplicate groups exist. {details}. Run "
            "`python manage.py audit_duplicate_publish_tasks`, manually reconcile "
            "the listed task IDs, then retry the migration. No records were changed."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0005_publishattempt_provider_call_started_at_and_more"),
    ]

    operations = [
        migrations.RunPython(
            precheck_duplicate_live_tasks,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="publishtask",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            *LIVE_STATUSES,
                        ),
                    )
                ),
                fields=(
                    "organization",
                    "platform_content",
                    "content_version",
                    "social_account",
                ),
                name="publishing_unique_live_content_account",
            ),
        ),
    ]
