# Generated by Django 5.2.7 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0005_publishattempt_provider_call_started_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="publishtask",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "SCHEDULED",
                            "QUEUED",
                            "RUNNING",
                            "SUBMITTED",
                            "SUBMISSION_UNKNOWN",
                            "SUCCEEDED",
                        ),
                    )
                ),
                fields=(
                    "organization",
                    "platform_content",
                    "content_version",
                    "social_account",
                ),
                name="publishing_unique_live_content_account",
            ),
        ),
    ]
