# Generated by Django 5.2.17 on 2026-08-20 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


LIVE_STATUSES = (
    'SCHEDULED', 'QUEUED', 'RUNNING', 'SUBMITTED',
    'SUBMISSION_UNKNOWN', 'NEEDS_ATTENTION', 'SUCCEEDED',
)


def precheck_live_duplicates(apps, schema_editor):
    PublishTask = apps.get_model('publishing', 'PublishTask')
    duplicate = (
        PublishTask.objects.filter(status__in=LIVE_STATUSES)
        .values('organization_id', 'platform_content_id', 'content_version', 'social_account_id')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
        .order_by('organization_id', 'platform_content_id')
        .first()
    )
    if duplicate is None:
        return
    task_rows = list(
        PublishTask.objects.filter(
            organization_id=duplicate['organization_id'],
            platform_content_id=duplicate['platform_content_id'],
            content_version=duplicate['content_version'],
            social_account_id=duplicate['social_account_id'],
            status__in=LIVE_STATUSES,
        ).values_list('id', 'status').order_by('created_at', 'id')
    )
    summary = ', '.join(f'{task_id}:{status}' for task_id, status in task_rows)
    raise RuntimeError(
        'Publishing reconciliation migration blocked by duplicate protected tasks. '
        f'Reconcile these task IDs and statuses before retrying: {summary}'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_mastercontent_archived_at_mastercontent_archived_by_and_more'),
        ('identity', '0015_refresh_mission_permissions'),
        ('platforms', '0011_providerconnectionevent'),
        ('publishing', '0006_publishtask_unique_live_content_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishReconciliationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('EXACT_ID', 'Exact provider id')], default='EXACT_ID', max_length=16)),
                ('provider', models.CharField(choices=[('BUFFER', 'Buffer')], default='BUFFER', max_length=16)),
                ('provider_submission_id', models.CharField(max_length=255)),
                ('observed_provider_status', models.CharField(blank=True, default='', max_length=32)),
                ('result', models.CharField(choices=[('DEFERRED', 'Deferred'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('NEEDS_ATTENTION', 'Needs attention'), ('STALE', 'Stale snapshot')], max_length=32)),
                ('safe_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('provider_post_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_channel_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_sent_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['publish_task_id', 'sequence_number'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.RunPython(precheck_live_duplicates, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='publishtask',
            name='publishing_unique_live_content_account',
        ),
        migrations.AddField(
            model_name='publishtask',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishtask',
            name='next_reconcile_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishtask',
            name='reconciliation_attempt_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publishtask',
            name='reconciliation_error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='publishattempt',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('SUBMITTED', 'Submitted'), ('SUBMISSION_UNKNOWN', 'Submission unknown'), ('NEEDS_ATTENTION', 'Needs attention'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('STALE', 'Stale')], max_length=32),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUBMITTED', 'Submitted'), ('SUBMISSION_UNKNOWN', 'Submission unknown'), ('NEEDS_ATTENTION', 'Needs attention'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='publishtask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('SCHEDULED', 'QUEUED', 'RUNNING', 'SUBMITTED', 'SUBMISSION_UNKNOWN', 'NEEDS_ATTENTION', 'SUCCEEDED'))), fields=('organization', 'platform_content', 'content_version', 'social_account'), name='publishing_unique_live_content_account'),
        ),
        migrations.AddField(
            model_name='publishreconciliationattempt',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization'),
        ),
        migrations.AddField(
            model_name='publishreconciliationattempt',
            name='publish_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_attempts', to='publishing.publishtask'),
        ),
        migrations.AddConstraint(
            model_name='publishreconciliationattempt',
            constraint=models.UniqueConstraint(fields=('publish_task', 'sequence_number'), name='publishing_unique_reconciliation_number'),
        ),
    ]
