# Generated by Django 5.2.17 on 2026-08-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0007_publishreconciliationattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishattempt',
            name='provider_request_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='publishreconciliationattempt',
            name='candidate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publishreconciliationattempt',
            name='candidate_set_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='publishreconciliationattempt',
            name='matched_provider_post_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='publishreconciliationattempt',
            name='query_window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishreconciliationattempt',
            name='query_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishtask',
            name='provider_request_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='publishreconciliationattempt',
            name='mode',
            field=models.CharField(choices=[('EXACT_ID', 'Exact provider id'), ('UNKNOWN_MATCH', 'Unknown submission match')], default='EXACT_ID', max_length=16),
        ),
        migrations.AlterField(
            model_name='publishreconciliationattempt',
            name='result',
            field=models.CharField(choices=[('DEFERRED', 'Deferred'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('NEEDS_ATTENTION', 'Needs attention'), ('STALE', 'Stale snapshot'), ('MATCHED', 'Unique match')], max_length=32),
        ),
    ]
