# Generated by Django 5.2.17 on 2026-08-20 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0008_publishattempt_provider_request_fingerprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publishreconciliationattempt',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publish_reconciliation_resolutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishreconciliationattempt',
            name='mode',
            field=models.CharField(choices=[('EXACT_ID', 'Exact provider id'), ('UNKNOWN_MATCH', 'Unknown submission match'), ('MANUAL', 'Manual resolution')], default='EXACT_ID', max_length=16),
        ),
    ]
