# Generated by Django 5.2.17 on 2026-08-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0009_publishreconciliationattempt_resolved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishreconciliationattempt',
            name='candidate_search_truncated',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
