# Generated by Django 5.2.17 on 2026-08-10 04:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('identity', '0011_refresh_phase_b1_permissions'),
        ('jobs', '0002_add_phase_b1_job_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('ACCOUNT', 'Account'), ('POST', 'Post'), ('KEYWORD', 'Keyword'), ('INDUSTRY_PAGE', 'Industry page')], max_length=16)),
                ('collection_mode', models.CharField(choices=[('MANUAL_URL', 'Manual URL'), ('SCREENSHOT', 'Screenshot'), ('FILE_IMPORT', 'File import'), ('PASTE', 'Paste'), ('OFFICIAL_API', 'Official API')], max_length=16)),
                ('platform', models.CharField(max_length=32)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('normalized_url', models.URLField(blank=True, max_length=2048)),
                ('label', models.CharField(max_length=255)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('capability_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_monitoring_targets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('API', 'API'), ('URL', 'URL'), ('SCREENSHOT', 'Screenshot'), ('CSV', 'CSV'), ('JSON', 'JSON'), ('PASTE', 'Paste')], max_length=16)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('PARTIAL_SUCCESS', 'Partial success'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=16)),
                ('input_reference', models.JSONField(blank=True, default=dict)),
                ('received_count', models.PositiveIntegerField(default=0)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('row_errors', models.JSONField(blank=True, default=list)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_ingestion_batches', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_batch', to='jobs.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('monitoring_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_batches', to='sources.monitoringtarget')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SourceContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=32)),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('canonical_url', models.URLField(max_length=2048)),
                ('author_public_name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('original_text', models.TextField(blank=True)),
                ('public_published_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Content hash must be lowercase SHA-256.')])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_source_contents', to=settings.AUTH_USER_MODEL)),
                ('monitoring_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_contents', to='sources.monitoringtarget')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SourceSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal_type', models.CharField(choices=[('COMMENT', 'Comment'), ('POST_AUTHOR', 'Post author'), ('CHANNEL_OWNER', 'Channel owner'), ('PROFILE_MATCH', 'Profile match'), ('MENTION', 'Mention'), ('HASHTAG_MATCH', 'Hashtag match')], max_length=16)),
                ('platform', models.CharField(max_length=32)),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_source_signals', to=settings.AUTH_USER_MODEL)),
                ('monitoring_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_signals', to='sources.monitoringtarget')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('source_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_signals', to='sources.sourcecontent')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SourceEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('PUBLIC_TEXT', 'Public text'), ('PUBLIC_METADATA', 'Public metadata'), ('SCREENSHOT', 'Screenshot'), ('IMPORT_ROW', 'Import row')], max_length=16)),
                ('original_text', models.TextField(blank=True)),
                ('translated_text', models.TextField(blank=True)),
                ('translated_language', models.CharField(blank=True, max_length=16)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('platform', models.CharField(max_length=32)),
                ('public_published_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection_method', models.CharField(choices=[('API', 'API'), ('URL', 'URL'), ('SCREENSHOT', 'Screenshot'), ('CSV', 'CSV'), ('JSON', 'JSON'), ('PASTE', 'Paste')], max_length=16)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('content_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Content hash must be lowercase SHA-256.')])),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOURCE_UNAVAILABLE', 'Source unavailable'), ('REDACTED_BY_RETENTION', 'Redacted by retention')], default='AVAILABLE', max_length=24)),
                ('retention_class', models.CharField(choices=[('TRANSIENT_30D', 'Transient 30 days'), ('CONFIRMED', 'Confirmed'), ('HANDOFF_PROTECTED', 'Handoff protected')], default='TRANSIENT_30D', max_length=24)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_source_evidence', to=settings.AUTH_USER_MODEL)),
                ('import_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_source_evidence', to='assets.materialasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('screenshot_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screenshot_source_evidence', to='assets.materialasset')),
                ('source_signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='sources.sourcesignal')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='IngestionRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('normalized_input', models.JSONField()),
                ('outcome', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DUPLICATE', 'Duplicate'), ('FAILED', 'Failed')], max_length=16)),
                ('error', models.JSONField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='sources.ingestionbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('source_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_rows', to='sources.sourcecontent')),
                ('source_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_rows', to='sources.sourceevidence')),
                ('source_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_rows', to='sources.sourcesignal')),
            ],
            options={
                'ordering': ['batch_id', 'row_number'],
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='monitoringtarget',
            constraint=models.CheckConstraint(condition=models.Q(('external_reference__gt', ''), ('normalized_url__gt', ''), _connector='OR'), name='sources_target_has_locator'),
        ),
        migrations.AddConstraint(
            model_name='ingestionbatch',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='sources_unique_batch_key'),
        ),
        migrations.AddConstraint(
            model_name='sourcecontent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('organization', 'platform', 'external_id'), name='sources_unique_content_external'),
        ),
        migrations.AddConstraint(
            model_name='sourcecontent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', '')), fields=('organization', 'content_hash', 'canonical_url'), name='sources_unique_content_fallback'),
        ),
        migrations.AddConstraint(
            model_name='sourcesignal',
            constraint=models.CheckConstraint(condition=models.Q(('monitoring_target__isnull', False), ('source_content__isnull', False), _connector='OR'), name='sources_signal_has_source'),
        ),
        migrations.AddConstraint(
            model_name='sourcesignal',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('organization', 'platform', 'external_id'), name='sources_unique_signal_external'),
        ),
        migrations.AddConstraint(
            model_name='sourceevidence',
            constraint=models.UniqueConstraint(fields=('organization', 'content_hash'), name='sources_unique_evidence_hash'),
        ),
        migrations.AddConstraint(
            model_name='ingestionrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='sources_unique_batch_row'),
        ),
    ]
