# Generated by Django 5.2.17 on 2026-08-10 14:58

import django.core.validators
import hashlib
import json
from uuid import UUID
from django.db import migrations, models


def _digest(reference):
    encoded = json.dumps(
        reference,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def backfill_request_identity(apps, schema_editor):
    batch_model = apps.get_model("sources", "IngestionBatch")
    row_model = apps.get_model("sources", "IngestionRow")
    for batch in batch_model.objects.select_related("job").order_by("pk").iterator():
        snapshot = (
            batch.job.input_snapshot
            if batch.job_id and isinstance(batch.job.input_snapshot, dict)
            else {}
        )
        snapshot_digest = snapshot.get("prepared_reference_sha256")
        digest = (
            snapshot_digest
            if isinstance(snapshot_digest, str)
            and len(snapshot_digest) == 64
            and all(character in "0123456789abcdef" for character in snapshot_digest)
            else _digest(batch.input_reference)
        )
        raw_asset_id = snapshot.get("import_asset_id")
        if raw_asset_id is None and isinstance(batch.input_reference, dict):
            raw_asset_id = batch.input_reference.get("import_asset_id")
        try:
            asset_id = UUID(str(raw_asset_id)) if raw_asset_id is not None else None
        except (TypeError, ValueError, AttributeError):
            asset_id = None
        safe_reference = batch.input_reference
        if (
            isinstance(safe_reference, dict)
            and isinstance(safe_reference.get("retention"), dict)
            and safe_reference["retention"].get("reason")
            == "TRANSIENT_30D_EXPIRED"
        ):
            safe_reference = dict(safe_reference)
            linked_evidence = {
                row_number: str(evidence_id)
                for row_number, evidence_id in row_model.objects.filter(
                    batch_id=batch.pk,
                    source_evidence_id__isnull=False,
                ).values_list("row_number", "source_evidence_id")
            }
            retained_rows = []
            for row in safe_reference.get("rows", []):
                if not isinstance(row, dict):
                    continue
                row_number = row.get("row_number")
                evidence_id = linked_evidence.get(row_number)
                if evidence_id is None:
                    continue
                retained_rows.append(
                    {
                        "platform": row.get("platform", "MANUAL"),
                        "source_url": row.get("source_url", ""),
                        "signal_type": row.get("signal_type", "MENTION"),
                        "original_text": "",
                        "author_name": "",
                        "published_at": row.get("published_at"),
                        "screenshot_asset_id": None,
                        "row_number": row_number,
                        "retention": {
                            "schema": "SOURCE_RETENTION_TOMBSTONE_V1",
                            "status": "REDACTED_BY_RETENTION",
                            "reason": "TRANSIENT_30D_EXPIRED",
                            "source_evidence_id": evidence_id,
                        },
                    }
                )
            safe_reference["rows"] = retained_rows
            safe_reference.pop("import_asset_id", None)
            if retained_rows:
                safe_reference["retention"] = {
                    "schema": "SOURCE_RETENTION_TOMBSTONE_V1",
                    "status": "REDACTED_BY_RETENTION",
                    "reason": "TRANSIENT_30D_EXPIRED",
                    "redacted_row_numbers": sorted(
                        row["row_number"] for row in retained_rows
                    ),
                }
            else:
                safe_reference.pop("retention", None)
        batch_model.objects.filter(pk=batch.pk).update(
            prepared_reference_sha256=digest,
            request_import_asset_id=asset_id,
            input_reference=safe_reference,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionbatch',
            name='prepared_reference_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Content hash must be lowercase SHA-256.')]),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='request_import_asset_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_request_identity, noop_reverse),
        migrations.AddConstraint(
            model_name="ingestionbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    prepared_reference_sha256__regex="^[0-9a-f]{64}$"
                ),
                name="sources_batch_request_digest_valid",
            ),
        ),
    ]
