# Generated by Django 5.2.17 on 2026-08-08 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret_reference', models.CharField(max_length=512)),
                ('granted_scopes', models.JSONField(default=list)),
                ('implementation_capabilities', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connector_credentials', to='platforms.platform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_definitions', to='platforms.platform')),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'code'), name='platforms_unique_capability')],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('publish_mode', models.CharField(choices=[('API_AUTO', 'API automatic'), ('API_CONFIRM', 'API confirmation'), ('EXPORT_PACKAGE', 'Export package'), ('MANUAL', 'Manual')], default='MANUAL', max_length=32)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to='platforms.connectorcredential')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_accounts', to='platforms.platform')),
            ],
            options={
                'ordering': ['display_name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'platform', 'external_id'), name='platforms_unique_social_account')],
            },
        ),
    ]
