# Generated by Django 5.2.17 on 2026-08-08 16:07

import apps.platforms.codes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_remove_connectorcredential_implementation_capabilities_alter_platformcapability_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectorcredential',
            name='granted_scopes',
            field=models.JSONField(default=list, validators=[apps.platforms.codes.validate_capability_list]),
        ),
    ]
