# Generated by Django 5.2.17 on 2026-08-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_alter_connectorcredential_granted_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='connector_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16),
        ),
    ]
