# Generated by Django 5.2 on 2026-08-14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0010_phaseae2eownership"),
        ("platforms", "0004_socialaccount_connector_metadata_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthConnectionAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_hash", models.CharField(max_length=64, unique=True)),
                ("return_path", models.CharField(max_length=512)),
                ("pkce_verifier_reference", models.CharField(blank=True, default="", max_length=512)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="platform_oauth_attempts", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="identity.organization")),
                ("platform", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="oauth_attempts", to="platforms.platform")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="oauthconnectionattempt",
            index=models.Index(fields=["organization", "platform", "expires_at"], name="platforms_oauth_org_exp_idx"),
        ),
    ]
