# Generated by Django 5.2 on 2026-08-15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

import apps.platforms.codes


class Migration(migrations.Migration):

    dependencies = [
        ("platforms", "0005_oauthconnectionattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountConnectionSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("secret_reference", models.CharField(max_length=512)),
                ("candidates", models.JSONField(default=list)),
                ("granted_capabilities", models.JSONField(default=list, validators=[apps.platforms.codes.validate_capability_list])),
                ("credential_expires_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_candidate_id", models.CharField(blank=True, default="", max_length=64)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="platform_connection_sessions", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="identity.organization")),
                ("platform", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="connection_sessions", to="platforms.platform")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="accountconnectionsession",
            index=models.Index(fields=["organization", "platform", "expires_at"], name="platforms_connect_org_exp_idx"),
        ),
    ]
