# Generated by Django 5.2.17 on 2026-08-15 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_phaseae2eownership'),
        ('platforms', '0006_accountconnectionsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedOAuthCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=96, unique=True)),
                ('actor_identifier', models.CharField(max_length=64)),
                ('platform_code', models.CharField(max_length=64)),
                ('connection_attempt_id', models.UUIDField()),
                ('account_binding', models.CharField(blank=True, default='', max_length=255)),
                ('ciphertext', models.BinaryField(blank=True, default=bytes)),
                ('nonce', models.BinaryField(blank=True, default=bytes)),
                ('key_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ROTATED', 'Rotated'), ('DISCONNECTED', 'Disconnected')], default='ACTIVE', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'platform_code', 'status'], name='platforms_oauth_vault_idx')],
            },
        ),
    ]
