# Generated by Django 5.2.17 on 2026-08-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0007_encryptedoauthcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='connection_state',
            field=models.CharField(choices=[('CONFIGURATION_REQUIRED', 'Configuration required'), ('CONNECTED', 'Connected'), ('REFRESH_DUE', 'Refresh due'), ('REAUTHORIZATION_REQUIRED', 'Reauthorization required'), ('INSUFFICIENT_CAPABILITY', 'Insufficient capability'), ('PROVIDER_UNAVAILABLE', 'Provider unavailable'), ('DISCONNECTED', 'Disconnected')], default='CONFIGURATION_REQUIRED', max_length=32),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_probe_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_refresh_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='lifecycle_error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='reauthorization_required_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
