# Generated by Django 5.2.17 on 2026-08-19 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _backfill_direct(apps, schema_editor):
    del schema_editor
    SocialAccount = apps.get_model("platforms", "SocialAccount")
    SocialAccount.objects.filter(provider__isnull=True).update(provider="DIRECT")


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_refresh_mission_permissions'),
        ('platforms', '0008_socialaccount_connection_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('BUFFER', 'Buffer')], max_length=32)),
                ('credential_reference', models.CharField(blank=True, default='', max_length=512)),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('granted_scopes', models.JSONField(blank=True, default=list)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('connection_state', models.CharField(choices=[('CONFIGURATION_REQUIRED', 'Configuration required'), ('CONNECTED', 'Connected'), ('REFRESH_DUE', 'Refresh due'), ('REAUTHORIZATION_REQUIRED', 'Reauthorization required'), ('INSUFFICIENT_CAPABILITY', 'Insufficient capability'), ('PROVIDER_UNAVAILABLE', 'Provider unavailable'), ('DISCONNECTED', 'Disconnected')], default='CONFIGURATION_REQUIRED', max_length=32)),
                ('last_probe_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('reauthorization_required_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('lifecycle_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(
                choices=[('DIRECT', 'Direct'), ('BUFFER', 'Buffer')],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='provider_account_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='provider_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='social_accounts', to='platforms.providerconnection'),
        ),
        migrations.RunPython(_backfill_direct, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(
                choices=[('DIRECT', 'Direct'), ('BUFFER', 'Buffer')],
                default='DIRECT',
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_connection__isnull', False)), fields=('organization', 'provider_connection', 'provider_account_id'), name='platforms_unique_buffer_channel'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('provider', 'DIRECT'), ('provider_account_id', ''), ('provider_connection__isnull', True)), models.Q(('provider', 'BUFFER'), ('provider_connection__isnull', False), models.Q(('provider_account_id', ''), _negated=True)), _connector='OR'), name='platforms_social_account_provider_shape'),
        ),
        migrations.AddConstraint(
            model_name='providerconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'provider'), name='platforms_unique_provider_connection'),
        ),
    ]
