# Generated by Django 5.2.17 on 2026-08-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_refresh_mission_permissions'),
        ('platforms', '0009_socialaccount_provider_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialaccount',
            name='platforms_social_account_provider_shape',
        ),
        migrations.AddConstraint(
            model_name='providerconnection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('connection_state', 'CONNECTED'), _negated=True), models.Q(models.Q(('credential_reference', ''), _negated=True), models.Q(('external_id', ''), _negated=True)), _connector='OR'), name='platforms_provider_connection_connected_shape'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('provider', 'DIRECT'), ('provider_account_id', ''), ('provider_connection__isnull', True)), models.Q(('credential__isnull', True), ('provider', 'BUFFER'), ('provider_connection__isnull', False), models.Q(('provider_account_id', ''), _negated=True)), _connector='OR'), name='platforms_social_account_provider_shape'),
        ),
    ]
