# Generated by Django 5.2.17 on 2026-08-19 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_refresh_mission_permissions'),
        ('platforms', '0010_remove_socialaccount_platforms_social_account_provider_shape_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConnectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('action', models.CharField(choices=[('CONNECT', 'Connect'), ('ROTATE', 'Rotate'), ('PROBE', 'Probe'), ('SYNC', 'Sync'), ('DISCONNECT', 'Disconnect')], max_length=32)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_connection_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_connection_events', to='identity.organization')),
                ('provider_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='platforms.providerconnection')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['organization', 'provider', '-created_at'], name='platforms_provconn_evt_org_idx')],
            },
        ),
    ]
