import { QueryClient, VueQueryPlugin } from "@tanstack/vue-query"
import { render, screen } from "@testing-library/vue"
import userEvent from "@testing-library/user-event"
import { afterEach, expect, it, vi } from "vitest"
import { currentUserQueryOptions } from "../auth/auth"
import AnalyticsPage from "./AnalyticsPage.vue"

it("announces the exact click total and provides an accessible data table",async()=>{vi.stubGlobal("fetch",vi.fn((path:string)=>Promise.resolve(new Response(JSON.stringify(path.startsWith("/api/v1/analytics")?{count:1,total_clicks:17,next:null,previous:null,results:[{date:"2026-08-10",campaign_id:"camp",platform_id:"p",country:"DE",product_id:"prod",clicks:17}]}:{next:null,previous:null,results:[]}),{status:200,headers:{"Content-Type":"application/json"}}))));const client=new QueryClient({defaultOptions:{queries:{retry:false}}});client.setQueryData(currentUserQueryOptions().queryKey,{user:{id:1,username:"reader"},organization:{id:"o1",name:"Org",slug:"org"},membership:{id:"m",role:"READ_ONLY",status:"ACTIVE",permissions:["publishing.read"]}});render(AnalyticsPage,{global:{plugins:[[VueQueryPlugin,{queryClient:client}]]}});expect(await screen.findByLabelText("总点击数")).toHaveTextContent("17");expect(screen.getByRole("table",{name:"渠道点击明细"})).toBeInTheDocument()})

afterEach(()=>vi.unstubAllGlobals())
function renderAnalytics(fetch:ReturnType<typeof vi.fn>,org="o1"){vi.stubGlobal("fetch",fetch);const client=new QueryClient({defaultOptions:{queries:{retry:false}}});client.setQueryData(currentUserQueryOptions().queryKey,{user:{id:1,username:"reader"},organization:{id:org,name:"Org",slug:"org"},membership:{id:"m",role:"READ_ONLY",status:"ACTIVE",permissions:["publishing.read"]}});render(AnalyticsPage,{global:{plugins:[[VueQueryPlugin,{queryClient:client}]]}});return client}
it("reports clipboard failure without navigating",async()=>{Object.defineProperty(navigator,"clipboard",{configurable:true,value:{writeText:vi.fn().mockRejectedValue(new Error("denied"))}});const fetch=vi.fn((path:string)=>Promise.resolve(new Response(JSON.stringify(path.startsWith("/api/v1/analytics")?{count:0,total_clicks:0,next:null,previous:null,results:[]}:path==="/api/v1/tracking-links"?{next:null,previous:null,results:[{id:"l",utm_campaign:"launch",full_url:"https://example.com/?utm_source=x"}]}:{next:null,previous:null,results:[]}),{status:200,headers:{"Content-Type":"application/json"}})));renderAnalytics(fetch);await userEvent.click(await screen.findByRole("button",{name:"复制"}));expect(screen.getByRole("status")).toHaveTextContent("复制失败")})
it("shows a named retry for a 503 summary",async()=>{const fetch=vi.fn((path:string)=>Promise.resolve(path.startsWith("/api/v1/analytics")?new Response(null,{status:503}):new Response(JSON.stringify({next:null,previous:null,results:[]}),{status:200,headers:{"Content-Type":"application/json"}})));renderAnalytics(fetch);expect(await screen.findByRole("alert")).toHaveTextContent("分析数据没有加载成功");expect(screen.getByRole("button",{name:"重新加载分析数据"})).toBeInTheDocument()})
it("derives and locks tracking provenance through the published content chain",async()=>{document.cookie="csrftoken=t; path=/";const fetch=vi.fn((path:string,init?:RequestInit)=>{let payload:unknown={next:null,previous:null,results:[]};if(path.startsWith("/api/v1/analytics"))payload={count:0,total_clicks:0,next:null,previous:null,results:[]};if(path==="/api/v1/publish-tasks")payload={next:null,previous:null,results:[{id:"task",platform_content_id:"pc",platform_id:"platform",published_post:{id:"post",external_id:"remote-1"}}]};if(path==="/api/v1/platform-contents/pc")payload={id:"pc",master_content_id:"master"};if(path==="/api/v1/master-contents/master")payload={id:"master",brief_id:"brief"};if(path==="/api/v1/content-briefs/brief")payload={id:"brief",campaign_id:"campaign",product_ids:["product"],landing_page_url:"https://example.com/gear"};if(path==="/api/v1/tracking-links"&&init?.method==="POST")payload={id:"link",full_url:"https://example.com/gear?utm_source=linkedin"};return Promise.resolve(new Response(JSON.stringify(payload),{status:200,headers:{"Content-Type":"application/json"}}))});renderAnalytics(fetch);await userEvent.click(await screen.findByRole("button",{name:"创建追踪链接"}));await userEvent.selectOptions(screen.getByLabelText("已发布内容"),"task");await userEvent.type(screen.getByLabelText("来源"),"linkedin");await userEvent.clear(screen.getByLabelText("媒介"));await userEvent.type(screen.getByLabelText("媒介"),"social");await userEvent.type(screen.getByLabelText("活动标识"),"launch");await userEvent.click(screen.getByRole("button",{name:"创建"}));expect(await screen.findByRole("status")).toHaveTextContent("追踪链接已创建");const call=fetch.mock.calls.find(item=>item[0]==="/api/v1/tracking-links"&&item[1]?.method==="POST")!;expect(JSON.parse(call[1].body)).toEqual({destination:"https://example.com/gear",utm_source:"linkedin",utm_medium:"social",utm_campaign:"launch",campaign_id:"campaign",platform_id:"platform",product_id:"product",published_post_id:"post"})})
