import { afterEach, expect, it, vi } from "vitest"
import { approvedCurrentHeads, cancelPublish,getPublishCalendar,getPublishTaskPage,isEligiblePublishingPair,localMonthRange,retryPublish,schedulePublish,shouldPollPublishTasks } from "./api"
afterEach(()=>{vi.unstubAllGlobals();document.cookie="csrftoken=; Max-Age=0; path=/"})
const json=(value:unknown)=>new Response(JSON.stringify(value),{status:200,headers:{"Content-Type":"application/json"}})
it("requests an explicit calendar range and browser timezone",async()=>{const fetch=vi.fn().mockResolvedValue(json({days:[]}));vi.stubGlobal("fetch",fetch);await getPublishCalendar({start:"2026-08-01T00:00:00.000Z",end:"2026-09-01T00:00:00.000Z",timezone:"Asia/Shanghai",account:"a"});expect(fetch.mock.calls[0][0]).toContain("timezone=Asia%2FShanghai");expect(fetch.mock.calls[0][0]).toContain("account=a")})
it("schedules with the exact body and stable supplied idempotency key",async()=>{document.cookie="csrftoken=t; path=/";const fetch=vi.fn().mockResolvedValue(json({id:"t"}));vi.stubGlobal("fetch",fetch);const input={platform_content_id:"c",social_account_id:"a",scheduled_at:"2026-08-10T08:00:00.000Z",timezone:"Asia/Shanghai"};await schedulePublish(input,"stable-key");const init=fetch.mock.calls[0][1] as RequestInit;expect(JSON.parse(init.body as string)).toEqual(input);expect(new Headers(init.headers).get("Idempotency-Key")).toBe("stable-key")})
it("guards page-two paths and sends empty cancel/retry actions",async()=>{document.cookie="csrftoken=t; path=/";const fetch=vi.fn().mockImplementation(()=>Promise.resolve(json({next:null,previous:null,results:[]})));vi.stubGlobal("fetch",fetch);await getPublishTaskPage("/api/v1/publish-tasks?cursor=n");await cancelPublish("t");await retryPublish("t");expect(fetch.mock.calls.map(c=>c[0])).toEqual(["/api/v1/publish-tasks?cursor=n","/api/v1/publish-tasks/t/cancel","/api/v1/publish-tasks/t/retry"]);await expect(getPublishTaskPage("/api/v1/tracking-links?cursor=x")).rejects.toBeDefined()})
it("uses local calendar month boundaries instead of UTC calendar boundaries",()=>{const range=localMonthRange(new Date(2026,7,15,12),"Asia/Shanghai");expect(range.start).toBe(new Date(2026,7,1).toISOString());expect(range.end).toBe(new Date(2026,8,1).toISOString())})
it("keeps only approved canonical heads and rejects an approved predecessor with an off-page successor",()=>{const base={master_content_id:"m",master_version:1,platform_id:"p",payload:{title:"",body:"",cta:"",concept_codes:[],platform_code:"x"},provenance:{},created_by_id:1,created_at:"",updated_at:""};const old={...base,id:"old",lineage_id:"line",previous_version_id:null,version:1,status:"APPROVED",is_current_head:true};const successor={...base,id:"new",lineage_id:"line",previous_version_id:"old",version:2,status:"DRAFT",is_current_head:true};expect(approvedCurrentHeads([old,successor] as never)).toEqual([])})
it("requires an active API-auto account on the same platform with PUBLISH",()=>{const content={platform_id:"p",status:"APPROVED",is_current_head:true};const good={platform_id:"p",status:"ACTIVE",publish_mode:"API_AUTO",effective_capabilities:["PUBLISH"]};expect(isEligiblePublishingPair(content as never,good as never)).toBe(true);for(const account of [{...good,platform_id:"other"},{...good,status:"INACTIVE"},{...good,publish_mode:"MANUAL"},{...good,effective_capabilities:[]}])expect(isEligiblePublishingPair(content as never,account as never)).toBe(false)})
it("polls only executable work and never a future scheduled/retry task",()=>{const now=new Date("2026-08-10T00:00:00Z");expect(shouldPollPublishTasks([{status:"QUEUED"}] as never,now)).toBe(true);expect(shouldPollPublishTasks([{status:"SCHEDULED",scheduled_at:"2026-08-11T00:00:00Z"}] as never,now)).toBe(false);expect(shouldPollPublishTasks([{status:"RETRY_QUEUED",retry_not_before:"2026-08-11T00:00:00Z"}] as never,now)).toBe(false);expect(shouldPollPublishTasks([{status:"RETRY_QUEUED",retry_not_before:"2026-08-09T00:00:00Z"}] as never,now)).toBe(true)})
