import { QueryClient, VueQueryPlugin } from "@tanstack/vue-query"
import { render, screen } from "@testing-library/vue"
import userEvent from "@testing-library/user-event"
import { afterEach, expect, it, vi } from "vitest"
import { currentUserQueryOptions } from "../auth/auth"
import PublishingCalendarPage from "./PublishingCalendarPage.vue"

it("shows the calendar timezone, task status, and scheduling action",async()=>{vi.stubGlobal("fetch",vi.fn((path:string)=>Promise.resolve(new Response(JSON.stringify(path.startsWith("/api/v1/publish-calendar")?{timezone:"Asia/Shanghai",start:"2026-08-01T00:00:00Z",end:"2026-09-01T00:00:00Z",metadata:{max_entries:100,returned_entries:1,truncated:false},days:[{date:"2026-08-10",entries:[{id:"t1",platform_content_id:"c1",social_account_id:"a1",platform_id:"p1",status:"SCHEDULED",scheduled_at:"2026-08-10T08:00:00Z",attempt_number:0,attempts:[]}]}]}:{next:null,previous:null,results:[]}),{status:200,headers:{"Content-Type":"application/json"}}))));const client=new QueryClient({defaultOptions:{queries:{retry:false}}});client.setQueryData(currentUserQueryOptions().queryKey,{user:{id:1,username:"op"},organization:{id:"o1",name:"Org",slug:"org"},membership:{id:"m",role:"OPERATOR",status:"ACTIVE",permissions:["publishing.read","publishing.manage"]}});render(PublishingCalendarPage,{global:{plugins:[[VueQueryPlugin,{queryClient:client}]]}});expect(await screen.findByText("SCHEDULED")).toBeInTheDocument();expect(screen.getByText(/Asia\/Shanghai/)).toBeInTheDocument();expect(screen.getByRole("button",{name:"安排发布"})).toBeInTheDocument()})

afterEach(()=>vi.unstubAllGlobals())
function renderPublishing(permissions:string[],fetch:ReturnType<typeof vi.fn>){vi.stubGlobal("fetch",fetch);const client=new QueryClient({defaultOptions:{queries:{retry:false}}});client.setQueryData(currentUserQueryOptions().queryKey,{user:{id:1,username:"user"},organization:{id:"o1",name:"Org",slug:"org"},membership:{id:"m",role:"READ_ONLY",status:"ACTIVE",permissions}});render(PublishingCalendarPage,{global:{plugins:[[VueQueryPlugin,{queryClient:client}]]}})}
it("announces a truncated calendar and explains when no account can publish",async()=>{const calendar={timezone:"UTC",start:"2026-08-01T00:00:00Z",end:"2026-09-01T00:00:00Z",metadata:{max_entries:2,returned_entries:2,truncated:true},days:[]};const fetch=vi.fn((path:string)=>Promise.resolve(new Response(JSON.stringify(path.startsWith("/api/v1/publish-calendar")?calendar:path==="/api/v1/social-accounts"?{results:[{id:"a",status:"ACTIVE",effective_capabilities:[],display_name:"Manual"}]}:{next:null,previous:null,results:[]}),{status:200,headers:{"Content-Type":"application/json"}})));renderPublishing(["publishing.read","publishing.manage"],fetch);expect(await screen.findByText(/前 2 条/)).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"安排发布"}));expect(screen.getByText(/没有可自动发布的账户/)).toBeInTheDocument();expect(screen.getByRole("button",{name:"确认安排"})).toBeDisabled()})
it("hides schedule and task actions from publishing readers",async()=>{const calendar={timezone:"UTC",start:"2026-08-01T00:00:00Z",end:"2026-09-01T00:00:00Z",metadata:{max_entries:100,returned_entries:1,truncated:false},days:[{date:"2026-08-10",entries:[{id:"t",status:"SCHEDULED",scheduled_at:"2026-08-10T00:00:00Z",attempts:[]}]}]};const fetch=vi.fn((path:string)=>Promise.resolve(new Response(JSON.stringify(path.startsWith("/api/v1/publish-calendar")?calendar:{next:null,previous:null,results:[]}),{status:200,headers:{"Content-Type":"application/json"}})));renderPublishing(["publishing.read"],fetch);expect(await screen.findByText("SCHEDULED")).toBeInTheDocument();expect(screen.queryByRole("button",{name:"安排发布"})).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"取消"})).not.toBeInTheDocument()})
it("shows a named retry for a 503 calendar",async()=>{const fetch=vi.fn((path:string)=>Promise.resolve(path.startsWith("/api/v1/publish-calendar")?new Response(null,{status:503}):new Response(JSON.stringify({next:null,previous:null,results:[]}),{status:200,headers:{"Content-Type":"application/json"}})));renderPublishing(["publishing.read"],fetch);expect(await screen.findByRole("alert")).toHaveTextContent("日历没有加载成功");expect(screen.getByRole("button",{name:"重新加载日历"})).toBeInTheDocument()})
