<script setup lang="ts">
import { computed, ref } from "vue"
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query"
import { ApiError } from "../../api/client"
import { currentUserQueryOptions } from "../auth/auth"
import { listPlatformContents } from "../content/api"
import { listSocialAccounts } from "../platformAccounts/api"
import { cancelPublish,getPublishCalendar,getPublishTaskPage,listPublishTasks,publishingKeys,retryPublish,schedulePublish } from "./api"
const client=useQueryClient(),user=useQuery(currentUserQueryOptions()),open=ref(false),contentId=ref(""),accountId=ref(""),localTime=ref(""),message=ref(""),pageUrl=ref<string|null>(null)
const org=computed(()=>user.data.value?.organization.id??""),canManage=computed(()=>user.data.value?.membership.permissions.includes("publishing.manage")??false)
const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC",anchor=ref(new Date()),monthLabel=computed(()=>anchor.value.toLocaleDateString("zh-CN",{year:"numeric",month:"long"}))
const range=computed(()=>{const start=new Date(Date.UTC(anchor.value.getFullYear(),anchor.value.getMonth(),1));const end=new Date(Date.UTC(anchor.value.getFullYear(),anchor.value.getMonth()+1,1));return{start:start.toISOString(),end:end.toISOString(),timezone}})
const calendar=useQuery({queryKey:computed(()=>publishingKeys.calendar(org.value,range.value.start)),queryFn:()=>getPublishCalendar(range.value),enabled:computed(()=>Boolean(org.value))})
const tasks=useQuery({queryKey:computed(()=>[...publishingKeys.tasks(org.value),pageUrl.value]),queryFn:()=>pageUrl.value?getPublishTaskPage(pageUrl.value):listPublishTasks(),enabled:computed(()=>Boolean(org.value)),refetchInterval:query=>query.state.data?.results.some(t=>["QUEUED","RUNNING","SCHEDULED","RETRY_QUEUED"].includes(t.status))?5000:false})
const contents=useQuery({queryKey:computed(()=>[...publishingKeys.all(org.value),"contents"]),queryFn:()=>listPlatformContents({status:"APPROVED"}),enabled:computed(()=>Boolean(org.value)&&canManage.value)})
const accounts=useQuery({queryKey:computed(()=>[...publishingKeys.all(org.value),"accounts"]),queryFn:listSocialAccounts,enabled:computed(()=>Boolean(org.value)&&canManage.value)})
const eligible=computed(()=>accounts.data.value?.filter(a=>a.status==="ACTIVE"&&a.effective_capabilities.includes("PUBLISH"))??[])
const refresh=()=>client.invalidateQueries({queryKey:publishingKeys.all(org.value)})
const schedule=useMutation({mutationFn:()=>schedulePublish({platform_content_id:contentId.value,social_account_id:accountId.value,scheduled_at:new Date(localTime.value).toISOString(),timezone},crypto.randomUUID()),onSuccess:async()=>{open.value=false;message.value="发布任务已安排。";await refresh()}})
const action=useMutation({mutationFn:({id,kind}:{id:string;kind:"cancel"|"retry"})=>kind==="cancel"?cancelPublish(id):retryPublish(id),onSettled:refresh})
const err=(v:unknown)=>v instanceof ApiError?v.userMessage:"发布数据暂时无法加载，请稍后重试。"
function move(delta:number){anchor.value=new Date(anchor.value.getFullYear(),anchor.value.getMonth()+delta,1)}
</script>
<template>
  <main class="page-stack">
    <header class="workspace-head"><div><p class="eyebrow">发布运营</p><h1>发布日历</h1><p>{{ monthLabel }} · 时区 {{ timezone }}</p></div><button v-if="canManage" class="primary-action" @click="open=true">安排发布</button></header><p v-if="message" role="status">{{ message }}</p><nav class="month-nav" aria-label="月份"><button @click="move(-1)">上个月</button><strong>{{ monthLabel }}</strong><button @click="move(1)">下个月</button></nav><p v-if="calendar.isPending.value" role="status">正在加载发布日历…</p><section v-else-if="calendar.isError.value" role="alert" class="panel"><h2>日历没有加载成功</h2><p>{{ err(calendar.error.value) }}</p><button @click="calendar.refetch()">重新加载日历</button></section><template v-else><p v-if="calendar.data.value?.metadata.truncated" role="status" class="warning">当前月份任务较多，日历仅展示前 {{ calendar.data.value.metadata.max_entries }} 条。</p><section class="agenda"><article v-for="day in calendar.data.value?.days" :key="day.date" class="panel"><h2>{{ day.date }}</h2><div v-for="entry in day.entries" :key="entry.id" class="task"><strong>{{ entry.status }}</strong><span>{{ new Date(entry.scheduled_at).toLocaleString() }}</span><div v-if="canManage" class="actions"><button v-if="['SCHEDULED','QUEUED','RETRY_QUEUED'].includes(entry.status)" @click="action.mutate({id:entry.id,kind:'cancel'})">取消</button><button v-if="entry.status==='FAILED'" @click="action.mutate({id:entry.id,kind:'retry'})">重试</button></div></div></article></section></template><section class="panel"><h2>最近任务</h2><p v-if="tasks.isError.value" role="alert">{{ err(tasks.error.value) }} <button @click="tasks.refetch()">重新加载任务</button></p><p v-else-if="!tasks.data.value?.results.length">暂无发布任务。</p><ul v-else><li v-for="task in tasks.data.value?.results" :key="task.id">{{ task.status }} · {{ new Date(task.scheduled_at).toLocaleString() }}</li></ul><nav class="actions" aria-label="发布任务分页"><button :disabled="!tasks.data.value?.previous" @click="pageUrl=tasks.data.value?.previous??null">上一页</button><button :disabled="!tasks.data.value?.next" @click="pageUrl=tasks.data.value?.next??null">下一页</button></nav></section>
    <div v-if="open" class="modal-backdrop" @click.self="open=false"><form class="modal panel" role="dialog" aria-modal="true" aria-labelledby="schedule-title" @submit.prevent="schedule.mutate()"><h2 id="schedule-title">安排发布</h2><label>已审核内容<select v-model="contentId" required><option value="" disabled>请选择</option><option v-for="item in contents.data.value?.results" :key="item.id" :value="item.id">{{ item.payload.title }}</option></select></label><label>可发布账户<select v-model="accountId" required><option value="" disabled>请选择</option><option v-for="item in eligible" :key="item.id" :value="item.id">{{ item.display_name }}</option></select></label><p v-if="!eligible.length">没有可自动发布的账户，请先到“平台账户”配置 PUBLISH 能力。</p><label>发布时间<input v-model="localTime" required type="datetime-local"></label><p v-if="schedule.isError.value" role="alert">{{ err(schedule.error.value) }}</p><div class="actions"><button type="button" @click="open=false">取消</button><button class="primary-action" :disabled="!eligible.length||schedule.isPending.value">确认安排</button></div></form></div>
  </main>
</template>
<style scoped>.workspace-head,.month-nav,.task,.actions{display:flex;justify-content:space-between;gap:1rem;align-items:center}.panel{padding:1.1rem;border:1px solid var(--border-color,#d8dee8);border-radius:1rem;background:white}.agenda{display:grid;gap:1rem}.task{padding:.7rem 0;border-top:1px solid #e5e9ef}.warning{padding:.8rem;background:#fff6d9}.modal-backdrop{position:fixed;inset:0;background:#0008;display:grid;place-items:center;padding:1rem;z-index:10}.modal{width:min(36rem,100%);display:grid;gap:1rem}.modal label{display:grid;gap:.35rem}.actions{justify-content:flex-end}@media(max-width:700px){.workspace-head,.task{display:grid}.month-nav{align-items:center}}</style>
