# Generated by Django 5.2.17 on 2026-08-09 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0002_add_airun_canceled_status'),
        ('campaigns', '0001_initial'),
        ('identity', '0007_refresh_content_permissions'),
        ('jobs', '0001_initial'),
        ('platforms', '0003_alter_connectorcredential_granted_scopes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brief_version', models.PositiveIntegerField()),
                ('lineage_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField()),
                ('provenance', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], max_length=16)),
                ('ai_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_contents', to='ai.airun')),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_contents', to='campaigns.contentbrief')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_content_versions', to=settings.AUTH_USER_MODEL)),
                ('generation_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_contents', to='jobs.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('previous_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_version', to='content.mastercontent')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PlatformContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_version', models.PositiveIntegerField()),
                ('lineage_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField()),
                ('provenance', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_content_versions', to=settings.AUTH_USER_MODEL)),
                ('master_content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_contents', to='content.mastercontent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_versions', to='platforms.platform')),
                ('previous_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_version', to='content.platformcontent')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='mastercontent',
            constraint=models.UniqueConstraint(fields=('lineage_id', 'version'), name='content_master_lineage_version'),
        ),
        migrations.AddConstraint(
            model_name='mastercontent',
            constraint=models.UniqueConstraint(condition=models.Q(('version', 1)), fields=('generation_job',), name='content_master_initial_job'),
        ),
        migrations.AddConstraint(
            model_name='mastercontent',
            constraint=models.UniqueConstraint(condition=models.Q(('version', 1)), fields=('ai_run',), name='content_master_initial_run'),
        ),
        migrations.AddConstraint(
            model_name='platformcontent',
            constraint=models.UniqueConstraint(fields=('lineage_id', 'version'), name='content_platform_lineage_version'),
        ),
        migrations.AddConstraint(
            model_name='platformcontent',
            constraint=models.UniqueConstraint(fields=('master_content', 'platform', 'version'), name='content_platform_master_target_version'),
        ),
    ]
