# Generated by Django 5.2.17 on 2026-08-15 16:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_concepts'),
        ('content', '0001_initial'),
        ('identity', '0010_phaseae2eownership'),
        ('jobs', '0003_alter_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_snapshot', models.JSONField()),
                ('provider_mode', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('FAKE_OFFLINE', 'Fake offline'), ('CONFIGURED_AI', 'Configured AI')], default='NOT_STARTED', max_length=32)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='QUEUED', max_length=16)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_content_recommendations', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='content_recommendation', to='jobs.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContentRecommendationOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('market_code', models.CharField(max_length=8)),
                ('language', models.CharField(max_length=16)),
                ('customer_profile', models.CharField(max_length=255)),
                ('channel_codes', models.JSONField(default=list)),
                ('theme', models.CharField(max_length=500)),
                ('rationale', models.TextField(max_length=2000)),
                ('evidence', models.JSONField(default=list)),
                ('missing_information', models.JSONField(default=list)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_recommendation_options', to='catalog.product')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='content.contentrecommendation')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_by_recommendations', to='content.contentrecommendationoption'),
        ),
        migrations.AddConstraint(
            model_name='contentrecommendationoption',
            constraint=models.UniqueConstraint(fields=('recommendation', 'position'), name='content_recommendation_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='contentrecommendationoption',
            constraint=models.UniqueConstraint(fields=('recommendation', 'product', 'market_code', 'language', 'customer_profile', 'theme'), name='content_recommendation_option_unique'),
        ),
    ]
