# Generated by Django 5.2.17 on 2026-08-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentrecommendation_contentrecommendationoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrecommendationoption',
            name='channel_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='contentrecommendationoption',
            name='evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='contentrecommendationoption',
            name='missing_information',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
