# Generated by Django 5.2.17 on 2026-08-15 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_brief_product_process_roles'),
        ('content', '0003_alter_contentrecommendationoption_channel_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrecommendation',
            name='selected_brief',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_content_recommendation', to='campaigns.contentbrief'),
        ),
    ]
