# Generated by Django 5.2.17 on 2026-08-15 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_contentrecommendation_selected_brief'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercontent',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastercontent',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_master_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mastercontent',
            name='archived_from_status',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
