# Generated by Django 5.2.17 on 2026-08-12 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0012_refresh_director_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_type', models.CharField(choices=[('PROMOTION_PLAN', 'Promotion plan'), ('CONTENT_APPROVAL', 'Content approval'), ('LEAD_HANDOFF', 'Lead handoff'), ('FACT_CONFLICT', 'Fact conflict'), ('COST_APPROVAL', 'Cost approval')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ADJUSTMENT_REQUESTED', 'Adjustment requested'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded'), ('EXPIRED', 'Expired')], default='PENDING', max_length=32)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('title_zh', models.CharField(max_length=160)),
                ('summary_zh', models.TextField()),
                ('reason_snapshot', models.JSONField(default=dict)),
                ('action_reference', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DirectorDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REQUEST_ADJUSTMENT', 'Request adjustment'), ('REJECT', 'Reject')], max_length=32)),
                ('proposal_version', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='director_decisions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='director.directorproposal')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='directorproposal',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 100)), name='director_proposal_priority_range'),
        ),
        migrations.AddConstraint(
            model_name='directorproposal',
            constraint=models.CheckConstraint(condition=models.Q(('title_zh', ''), _negated=True), name='director_proposal_title_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='directorproposal',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='director_proposal_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='directordecision',
            constraint=models.CheckConstraint(condition=models.Q(('proposal_version__gt', 0)), name='director_decision_proposal_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='directordecision',
            constraint=models.UniqueConstraint(fields=('proposal', 'proposal_version'), name='director_one_decision_per_proposal_version'),
        ),
    ]
