# Generated by Django 5.2.17 on 2026-08-14 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('is_demo', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TargetAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=96)),
                ('industry', models.CharField(blank=True, max_length=160)),
                ('employee_range', models.CharField(blank=True, max_length=64)),
                ('website', models.URLField(blank=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OutreachDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('english_draft', models.TextField()),
                ('chinese_explanation', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_drafts', to='growth.targetaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntentSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal_type', models.CharField(max_length=64)),
                ('source_label', models.CharField(max_length=255)),
                ('source_url', models.URLField()),
                ('evidence_text', models.TextField()),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intent_signals', to='growth.targetaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_label', models.CharField(max_length=255)),
                ('status', models.CharField(default='NEW', max_length=32)),
                ('is_demo', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_leads', to='growth.targetaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='OPEN', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='growth.targetaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role_title', models.CharField(blank=True, max_length=160)),
                ('public_contact_path', models.URLField(blank=True)),
                ('verification_status', models.CharField(default='PUBLIC_PATH', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='growth.targetaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='AWAITING_REVIEW', max_length=32)),
                ('is_demo', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='growth.targetaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldProvenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=160)),
                ('field_value', models.TextField()),
                ('source_label', models.CharField(max_length=255)),
                ('verification_status', models.CharField(max_length=32)),
                ('source_cost_micros', models.PositiveBigIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'field_name'), name='growth_unique_fact_field')],
            },
        ),
        migrations.AddConstraint(
            model_name='targetaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='growth_unique_account_name'),
        ),
        migrations.AddConstraint(
            model_name='followup',
            constraint=models.UniqueConstraint(fields=('organization', 'account'), name='growth_one_follow_up_per_account'),
        ),
    ]
