# Generated by Django 5.2.17 on 2026-08-14 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0001_initial'),
        ('identity', '0010_phaseae2eownership'),
        ('platforms', '0004_socialaccount_connector_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthPublishBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('PARTIAL_SUCCESS', 'Partial success'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CONFIGURATION_REQUIRED', 'Configuration required')], max_length=32)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='growth_publish_batches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GrowthPublishItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=32)),
                ('payload_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=16)),
                ('attempt_number', models.PositiveIntegerField(default=0)),
                ('external_post_id', models.CharField(blank=True, max_length=255)),
                ('external_post_url', models.URLField(blank=True)),
                ('last_error', models.JSONField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='growth.growthpublishbatch')),
                ('channel_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publish_items', to='growth.channelpackage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='growth_publish_items', to='platforms.socialaccount')),
            ],
            options={
                'ordering': ['channel', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='growthpublishbatch',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='growth_unique_publish_batch_key'),
        ),
        migrations.AddConstraint(
            model_name='growthpublishitem',
            constraint=models.UniqueConstraint(fields=('batch', 'channel'), name='growth_unique_publish_batch_channel'),
        ),
    ]
