# Generated by Django 5.2.17 on 2026-08-15 03:39

import apps.growth.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0003_intentsignal_evidence_metadata'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('source_code', models.CharField(default='TED', max_length=32)),
                ('cpv_codes', models.JSONField(default=apps.growth.models.default_gear_cpv_codes)),
                ('result_limit', models.PositiveSmallIntegerField(default=20)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='growth_discovery_profile', to='identity.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_code', models.CharField(max_length=32)),
                ('trigger', models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled')], max_length=16)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=16)),
                ('query_snapshot', models.JSONField(default=dict)),
                ('capability_snapshot', models.JSONField(default=dict)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('created_account_count', models.PositiveIntegerField(default=0)),
                ('created_signal_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='growth.discoveryprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
