# Generated by Django 5.2.17 on 2026-08-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0004_discoveryprofile_discoveryrun'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='intentsignal',
            constraint=models.UniqueConstraint(condition=models.Q(('content_hash', ''), _negated=True), fields=('organization', 'content_hash'), name='growth_unique_signal_evidence_hash'),
        ),
    ]
