# Generated by Django 5.2.17 on 2026-08-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0005_intentsignal_growth_unique_signal_evidence_hash'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='targetaccount',
            name='growth_unique_account_name',
        ),
        migrations.AddField(
            model_name='targetaccount',
            name='source_identity',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddConstraint(
            model_name='targetaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('source_identity', ''), _negated=True), fields=('organization', 'source_identity'), name='growth_unique_account_source_identity'),
        ),
    ]
