# Generated by Django 5.2.17 on 2026-08-15 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0012_discoverycandidate_review'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEnrichmentSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(default='FAKE_PREVIEW', max_length=24)),
                ('facts', models.JSONField(default=list)),
                ('public_contact_paths', models.JSONField(default=list)),
                ('uncertainties', models.JSONField(default=list)),
                ('evidence_envelope', models.JSONField(default=dict)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='enrichment_snapshot', to='growth.discoverycandidate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
