# Generated by Django 5.2.17 on 2026-08-15 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0013_candidate_enrichment_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateenrichmentsnapshot',
            name='target_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_enrichment_snapshot', to='growth.targetaccount'),
        ),
    ]
