# Generated by Django 5.2.17 on 2026-08-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0014_candidateenrichmentsnapshot_target_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcountryprofile',
            name='data_availability_label',
            field=models.CharField(default='待验证', max_length=64),
        ),
        migrations.AddField(
            model_name='marketcountryprofile',
            name='evidence_note',
            field=models.CharField(default='研究配置，尚无实时数据', max_length=255),
        ),
        migrations.AddField(
            model_name='marketcountryprofile',
            name='is_demo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketcountryprofile',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketcountryprofile',
            name='path_family',
            field=models.CharField(default='MIXED_ACQUISITION', max_length=32),
        ),
        migrations.AddField(
            model_name='marketcountryprofile',
            name='recommended_action',
            field=models.CharField(default='先导入许可名单或公开线索', max_length=160),
        ),
        migrations.AddField(
            model_name='marketcountryprofile',
            name='region',
            field=models.CharField(default='OTHER', max_length=32),
        ),
        migrations.AddField(
            model_name='marketcountryprofile',
            name='suitable_industries',
            field=models.JSONField(default=list),
        ),
    ]
