# Generated by Django 5.2.17 on 2026-08-15 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0015_marketcountryprofile_data_availability_label_and_more'),
        ('identity', '0010_phaseae2eownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactivationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_source', models.CharField(choices=[('EXISTING_CUSTOMER', 'Existing customer'), ('PAST_INQUIRY', 'Past inquiry'), ('TRADE_SHOW', 'Trade show'), ('OWNED_CRM', 'Owned CRM')], max_length=32)),
                ('last_interacted_at', models.DateTimeField()),
                ('interaction_summary', models.TextField()),
                ('relationship_confirmed', models.BooleanField(default=False)),
                ('tier', models.CharField(choices=[('STRATEGIC', 'Strategic'), ('NURTURE', 'Nurture'), ('OBSERVATION', 'Observation')], max_length=16)),
                ('status', models.CharField(choices=[('SELECTED', 'Selected'), ('DRAFTED', 'Drafted'), ('APPROVED', 'Approved')], default='SELECTED', max_length=16)),
                ('is_demo', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reactivations', to='growth.targetaccount')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reactivation_records', to='growth.outreachdraft')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_reactivations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountFunnelEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('REACTIVATION_SELECTED', 'Reactivation selected'), ('REACTIVATION_DRAFTED', 'Reactivation drafted'), ('REACTIVATION_APPROVED', 'Reactivation approved')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funnel_events', to='growth.targetaccount')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growth_account_funnel_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('reactivation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='growth.reactivationrecord')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='reactivationrecord',
            constraint=models.UniqueConstraint(fields=('organization', 'account'), name='growth_one_reactivation_per_account'),
        ),
        migrations.AddConstraint(
            model_name='accountfunnelevent',
            constraint=models.UniqueConstraint(fields=('reactivation', 'event_type'), name='growth_one_reactivation_event_type'),
        ),
    ]
