# Generated by Django 5.2.17 on 2026-08-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("growth", "0016_reactivationrecord_accountfunnelevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelpackage",
            name="source_platform_content",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="growth_channel_package",
                to="content.platformcontent",
            ),
        ),
    ]
