# Generated by Django 5.2.17 on 2026-08-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0019_trade_sync_run_trade_dataset_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedatasetsnapshot',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
