# Generated by Django 5.2.17 on 2026-08-15 21:17

import apps.growth.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0020_trade_snapshot_demo_flag'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMapsDiscoveryConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('api_key_ciphertext', models.TextField(blank=True)),
                ('api_key_key_version', models.PositiveSmallIntegerField(default=1)),
                ('cities', models.JSONField(default=apps.growth.models.default_maps_cities)),
                ('keywords', models.JSONField(default=apps.growth.models.default_maps_keywords)),
                ('radius_km', models.PositiveSmallIntegerField(default=50)),
                ('daily_quota', models.PositiveSmallIntegerField(default=500)),
                ('schedule_time', models.CharField(default='02:00', max_length=5)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='google_maps_discovery_config', to='identity.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
