# Generated by Django 5.2.17 on 2026-08-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0021_googlemapsdiscoveryconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverycandidate',
            name='grade',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='discoverycandidate',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discoverycandidate',
            name='score_breakdown',
            field=models.JSONField(default=dict),
        ),
    ]
