# Generated by Django 5.2.17 on 2026-08-15 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0022_discoverycandidate_grade_discoverycandidate_score_and_more'),
        ('identity', '0010_phaseae2eownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='discoverycandidate',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='growth_cand_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='discoverycandidate',
            index=models.Index(fields=['organization', '-created_at'], name='growth_cand_org_created_idx'),
        ),
    ]
