# Generated by Django 5.2.17 on 2026-08-15 23:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0023_discoverycandidate_growth_cand_org_status_idx_and_more'),
        ('identity', '0010_phaseae2eownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPlanApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('plan_snapshot', models.JSONField(default=dict)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='growth_promotion_plan_approvals', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_plan_approval', to='identity.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
