# Generated by Django 5.2.17 on 2026-08-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0024_promotionplanapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='stage',
            field=models.CharField(choices=[('DISCOVERED', 'Discovered'), ('QUALIFIED', 'Qualified'), ('ENRICHED', 'Enriched'), ('CONTACT_FOUND', 'Contact found'), ('EMAIL_VERIFIED', 'Email verified'), ('OUTREACH_READY', 'Outreach ready'), ('EMAIL_1_SENT', 'Email 1 sent'), ('OPENED', 'Opened'), ('SITE_VISITED', 'Site visited'), ('FOLLOW_UP_1', 'Follow up 1'), ('REPLIED', 'Replied'), ('RFQ', 'RFQ'), ('QUOTED', 'Quoted'), ('WON', 'Won'), ('LOST', 'Lost')], default='QUALIFIED', max_length=24),
        ),
    ]
