# Generated by Django 5.2.17 on 2026-08-15 23:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0025_followup_stage'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('QUOTE_CREATED', 'Quote created'), ('QUOTE_SENT', 'Quote sent'), ('NEGOTIATING', 'Negotiating'), ('WON', 'Won'), ('LOST', 'Lost'), ('NURTURE', 'Nurture')], default='QUOTE_CREATED', max_length=24)),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_deals', to='growth.targetaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
