# Generated by Django 5.2.17 on 2026-08-15 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0026_salesdeal'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCompanyMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('importer_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=3)),
                ('method', models.CharField(default='NO_MATCH', max_length=24)),
                ('confidence', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trade_company_matches', to='growth.targetaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
