# Generated by Django 5.2.17 on 2026-08-16 04:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0027_tradecompanymatch'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverycandidate',
            name='intent_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='discoverycandidate',
            name='intent_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LeadWebsiteVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=500)),
                ('utm_source', models.CharField(blank=True, max_length=64)),
                ('utm_campaign', models.CharField(blank=True, max_length=128)),
                ('session_id', models.CharField(blank=True, max_length=128)),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='website_visits', to='growth.discoverycandidate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
