# Generated by Django 5.2.17 on 2026-08-16 04:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0028_discoverycandidate_intent_breakdown_and_more'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundRfq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=96)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('industry', models.CharField(blank=True, max_length=160)),
                ('product_interest', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('file_names', models.JSONField(default=list)),
                ('need_slug', models.CharField(blank=True, max_length=32)),
                ('landing_page', models.CharField(blank=True, max_length=500)),
                ('lead_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='NEW', max_length=24)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
