# Generated by Django 5.2.17 on 2026-08-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0029_inboundrfq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InboundRfq',
        ),
    ]
