# Generated by Django 5.2.17 on 2026-08-17 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0030_delete_inboundrfq'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('goal', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('WAITING_APPROVAL', 'Waiting approval'), ('COMPLETED', 'Completed'), ('BUDGET_EXCEEDED', 'Budget exceeded'), ('FAILED', 'Failed')], default='RUNNING', max_length=24)),
                ('terminal_reason', models.CharField(blank=True, max_length=500)),
                ('max_steps', models.PositiveSmallIntegerField(default=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgentRunStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveSmallIntegerField()),
                ('tool_name', models.CharField(blank=True, max_length=160)),
                ('args', models.JSONField(default=dict)),
                ('outcome', models.CharField(max_length=32)),
                ('output', models.JSONField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=1000)),
                ('reasoning', models.TextField(blank=True)),
                ('approval_token', models.CharField(blank=True, max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='growth.agentrun')),
            ],
            options={
                'ordering': ['index', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='growth_unique_agent_run_key'),
        ),
        migrations.AddConstraint(
            model_name='agentrunstep',
            constraint=models.UniqueConstraint(fields=('run', 'index'), name='growth_unique_agent_run_step_index'),
        ),
    ]
