# Generated by Django 5.2.17 on 2026-08-17 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0031_agentrun_agentrunstep_and_more'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='stage',
            field=models.CharField(choices=[('DISCOVERED', 'Discovered'), ('QUALIFIED', 'Qualified'), ('ENRICHED', 'Enriched'), ('CONTACT_FOUND', 'Contact found'), ('EMAIL_VERIFIED', 'Email verified'), ('OUTREACH_READY', 'Outreach ready'), ('EMAIL_1_SENT', 'Email 1 sent'), ('OPENED', 'Opened'), ('SITE_VISITED', 'Site visited'), ('FOLLOW_UP_1', 'Follow up 1'), ('REPLIED', 'Replied'), ('BOUNCED', 'Bounced'), ('UNSUBSCRIBED', 'Unsubscribed'), ('RFQ', 'RFQ'), ('QUOTED', 'Quoted'), ('WON', 'Won'), ('LOST', 'Lost')], default='QUALIFIED', max_length=24),
        ),
        migrations.CreateModel(
            name='OutreachMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('REPLIED', 'Replied'), ('BOUNCED', 'Bounced'), ('UNSUBSCRIBED', 'Unsubscribed')], default='SENT', max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_messages', to='growth.targetaccount')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outreach_messages', to='growth.outreachdraft')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
