# Generated by Django 5.2.17 on 2026-08-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0032_alter_followup_stage_outreachmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundlead',
            name='route',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACQUISITION', 'Acquisition'), ('CUSTOMER_SERVICE', 'Customer service'), ('MANUAL_REVIEW', 'Manual review')], default='PENDING', max_length=24),
        ),
        migrations.AddField(
            model_name='inboundlead',
            name='route_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='inboundlead',
            name='routed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
