# Generated by Django 5.2.17 on 2026-08-17 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0033_inboundlead_route_inboundlead_route_reason_and_more'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServiceTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('AUTO_REPLY', 'Auto reply'), ('HUMAN_ESCALATION', 'Human escalation')], max_length=24)),
                ('draft_reply', models.TextField(blank=True)),
                ('reasoning', models.TextField(blank=True)),
                ('evidence', models.JSONField(default=dict)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_service_turns', to='growth.inboundlead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'lead'), name='growth_unique_customer_service_turn')],
            },
        ),
    ]
