# Generated by Django 5.2.17 on 2026-08-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0036_inboundrfq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('WAITING_APPROVAL', 'Waiting approval'), ('COMPLETED', 'Completed'), ('BUDGET_EXCEEDED', 'Budget exceeded'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='RUNNING', max_length=24),
        ),
    ]
