# Generated by Django 5.2.17 on 2026-08-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0037_alter_agentrun_status'),
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthpublishitem',
            name='publish_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_publish_items', to='publishing.publishtask'),
        ),
    ]
