# Generated by Django 5.2.17 on 2026-08-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0038_growthpublishitem_publish_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthpublishitem',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DELEGATED', 'Delegated'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=16),
        ),
    ]
