# Generated by Django 5.2.17 on 2026-08-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0039_alter_growthpublishitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='agent_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='resume_args',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
