# Generated by Django 5.2.17 on 2026-08-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0040_agentrun_agent_type_agentrun_resume_args'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundrfq',
            name='external_request_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='inboundrfq',
            constraint=models.UniqueConstraint(condition=models.Q(('external_request_id', ''), _negated=True), fields=('organization', 'external_request_id'), name='growth_unique_rfq_request_id'),
        ),
    ]
