# Generated by Django 5.2.17 on 2026-08-17 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0041_inboundrfq_external_request_id_and_more'),
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerserviceturn',
            name='growth_unique_customer_service_turn',
        ),
        migrations.AddField(
            model_name='customerserviceturn',
            name='rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_service_turns', to='growth.inboundrfq'),
        ),
        migrations.AddConstraint(
            model_name='customerserviceturn',
            constraint=models.UniqueConstraint(fields=('organization', 'rfq'), name='growth_unique_customer_service_rfq'),
        ),
    ]
