# Generated by Django 5.2.17 on 2026-08-17 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0043_backfill_agentrun_agent_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='approval_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_agent_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_agent_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_agent_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_agent_run_steps', to=settings.AUTH_USER_MODEL),
        ),
    ]
