# Generated by Django 5.2.17 on 2026-08-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0045_agentrun_execution_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachmessage',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('REPLIED', 'Replied'), ('BOUNCED', 'Bounced'), ('UNSUBSCRIBED', 'Unsubscribed')], default='SENT', max_length=24),
        ),
    ]
