# Generated by Django 5.2.17 on 2026-08-18 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_concepts'),
        ('growth', '0046_alter_outreachmessage_status'),
        ('identity', '0015_refresh_mission_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('target_countries', models.JSONField(default=list)),
                ('target_industries', models.JSONField(default=list)),
                ('customer_profile', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_account_count', models.PositiveIntegerField(default=0)),
                ('target_reply_count', models.PositiveIntegerField(default=0)),
                ('target_rfq_count', models.PositiveIntegerField(default=0)),
                ('budget_micros', models.PositiveBigIntegerField(default=0)),
                ('allowed_channels', models.JSONField(default=list)),
                ('attribution_code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=24)),
                ('health_status', models.CharField(choices=[('NORMAL', 'Normal'), ('ACTION_REQUIRED', 'Action required'), ('CHANNEL_BLOCKED', 'Channel blocked'), ('BUDGET_BLOCKED', 'Budget blocked'), ('DATA_INSUFFICIENT', 'Data insufficient'), ('FAILED', 'Failed')], default='DATA_INSUFFICIENT', max_length=24)),
                ('health_reason', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_growth_missions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('primary_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growth_missions', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MissionEntityLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('TARGET_ACCOUNT', 'Target account'), ('DISCOVERY_RUN', 'Discovery run'), ('AGENT_RUN', 'Agent run'), ('OUTREACH_DRAFT', 'Outreach draft'), ('CAMPAIGN', 'Campaign'), ('CHANNEL_PACKAGE', 'Channel package'), ('PUBLISH_BATCH', 'Publish batch'), ('METRIC_RECEIPT', 'Metric receipt'), ('SALES_DEAL', 'Sales deal')], max_length=32)),
                ('entity_id', models.UUIDField()),
                ('lane', models.CharField(choices=[('ACQUISITION', 'Acquisition'), ('OUTREACH', 'Outreach'), ('SOCIAL', 'Social'), ('ATTRIBUTION', 'Attribution')], max_length=16)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='growth_mission_links', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_links', to='growth.growthmission')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MissionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=16)),
                ('snapshot', models.JSONField(default=dict)),
                ('generation_mode', models.CharField(choices=[('AUTOMATION', 'Automation'), ('AI_GENERATION', 'AI generation')], max_length=24)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_mission_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_mission_plans', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='growth.growthmission')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['mission', 'version'],
            },
        ),
        migrations.AddConstraint(
            model_name='growthmission',
            constraint=models.UniqueConstraint(fields=('organization', 'attribution_code'), name='growth_unique_mission_attribution'),
        ),
        migrations.AddIndex(
            model_name='missionentitylink',
            index=models.Index(fields=['mission', 'lane'], name='mission_link_lane_idx'),
        ),
        migrations.AddIndex(
            model_name='missionentitylink',
            index=models.Index(fields=['entity_type', 'entity_id'], name='mission_link_entity_idx'),
        ),
        migrations.AddConstraint(
            model_name='missionentitylink',
            constraint=models.UniqueConstraint(fields=('organization', 'mission', 'entity_type', 'entity_id'), name='growth_unique_mission_entity_link'),
        ),
        migrations.AddIndex(
            model_name='missionplan',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='mission_plan_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='missionplan',
            constraint=models.UniqueConstraint(fields=('mission', 'version'), name='growth_unique_plan_version'),
        ),
    ]
