# Generated by Django 5.2.17 on 2026-08-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0047_growthmission_missionentitylink_missionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionentitylink',
            name='entity_type',
            field=models.CharField(choices=[('TARGET_ACCOUNT', 'Target account'), ('DISCOVERY_CANDIDATE', 'Discovery candidate'), ('DISCOVERY_RUN', 'Discovery run'), ('AGENT_RUN', 'Agent run'), ('OUTREACH_DRAFT', 'Outreach draft'), ('OUTREACH_MESSAGE', 'Outreach message'), ('CAMPAIGN', 'Campaign'), ('CONTENT_BRIEF', 'Content brief'), ('MASTER_CONTENT', 'Master content'), ('PLATFORM_CONTENT', 'Platform content'), ('CHANNEL_PACKAGE', 'Channel package'), ('PUBLISH_BATCH', 'Publish batch'), ('METRIC_RECEIPT', 'Metric receipt'), ('INBOUND_RFQ', 'Inbound RFQ'), ('SALES_DEAL', 'Sales deal')], max_length=32),
        ),
    ]
