# Generated by Django 5.2.17 on 2026-08-22 11:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


RLS_TABLES = (
    "growth_emailverificationrun",
    "growth_emailverificationevidence",
)
TENANT = "organization_id = app_current_organization_id()"
EVIDENCE_PARENT = (
    "organization_id = app_current_organization_id() AND EXISTS ("
    "SELECT 1 FROM growth_emailverificationrun parent "
    "WHERE parent.id = run_id "
    "AND parent.organization_id = app_current_organization_id())"
)
POLICY_CONTRACTS = {
    ("growth_emailverificationrun", "rls_growth_emailverificationrun_tenant_select"): (
        "SELECT", TENANT, None,
    ),
    ("growth_emailverificationrun", "rls_growth_emailverificationrun_tenant_insert"): (
        "INSERT", None, TENANT,
    ),
    ("growth_emailverificationrun", "rls_growth_emailverificationrun_tenant_update"): (
        "UPDATE", TENANT, TENANT,
    ),
    (
        "growth_emailverificationevidence",
        "rls_growth_emailverificationevidence_tenant_select",
    ): ("SELECT", TENANT, None),
    (
        "growth_emailverificationevidence",
        "rls_growth_emailverificationevidence_tenant_insert",
    ): ("INSERT", None, EVIDENCE_PARENT),
}


def enable_email_verification_rls(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in RLS_TABLES:
        schema_editor.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
        schema_editor.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
    for (table, policy), (command, using, check) in POLICY_CONTRACTS.items():
        clauses = [f'CREATE POLICY "{policy}" ON "{table}" FOR {command}']
        if using is not None:
            clauses.append(f"USING ({using})")
        if check is not None:
            clauses.append(f"WITH CHECK ({check})")
        schema_editor.execute(" ".join(clauses))


def disable_email_verification_rls(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    for table, policy in POLICY_CONTRACTS:
        schema_editor.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
    for table in RLS_TABLES:
        schema_editor.execute(f'ALTER TABLE "{table}" NO FORCE ROW LEVEL SECURITY')
        schema_editor.execute(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0049_agent_context_provenance'),
        ('identity', '0015_refresh_mission_permissions'),
        ('knowledge', '0008_harden_knowledge_rls_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normalized_email', models.CharField(blank=True, max_length=320)),
                ('email_fingerprint', models.CharField(max_length=64)),
                ('domain', models.CharField(blank=True, max_length=253)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('result_status', models.CharField(blank=True, choices=[('VALID', 'Valid'), ('LIKELY_VALID', 'Likely valid'), ('RISKY', 'Risky'), ('UNKNOWN', 'Unknown'), ('INVALID', 'Invalid')], max_length=16)),
                ('deliverability_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contact_quality_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('verifier_version', models.CharField(default='local-email-v1', max_length=64)),
                ('result_source', models.CharField(default='LOCAL', max_length=32)),
                ('requires_provider_review', models.BooleanField(default=False)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('safe_error_code', models.CharField(blank=True, max_length=64)),
                ('claim_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_verification_runs', to='growth.discoverycandidate')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_verification_runs', to='growth.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('check_type', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=64)),
                ('source_version', models.CharField(max_length=64)),
                ('outcome', models.CharField(max_length=32)),
                ('reason_code', models.CharField(max_length=64)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='growth.emailverificationrun')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='emailverificationrun',
            index=models.Index(fields=['organization', 'email_fingerprint', 'verifier_version'], name='growth_email_verify_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationrun',
            index=models.Index(fields=['organization', 'state', 'created_at'], name='growth_email_verify_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailverificationrun',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='growth_unique_email_verify_key'),
        ),
        migrations.AddConstraint(
            model_name='emailverificationrun',
            constraint=models.CheckConstraint(condition=models.Q(('deliverability_score__isnull', True), ('deliverability_score__lte', 100), _connector='OR'), name='growth_email_deliver_score_range'),
        ),
        migrations.AddConstraint(
            model_name='emailverificationrun',
            constraint=models.CheckConstraint(condition=models.Q(('contact_quality_score__isnull', True), ('contact_quality_score__lte', 100), _connector='OR'), name='growth_email_quality_score_range'),
        ),
        migrations.AddIndex(
            model_name='emailverificationevidence',
            index=models.Index(fields=['organization', 'run', 'sequence'], name='growth_email_evidence_run_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailverificationevidence',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='growth_unique_email_evidence_seq'),
        ),
        migrations.RunPython(
            enable_email_verification_rls,
            disable_email_verification_rls,
        ),
    ]
