from django.urls import path

from .views import (
    ChannelPackageApproveView,
    ChannelPackageBatchApproveView,
    ChannelPackageFromPlatformContentView,
    CandidateListImportView,
    CandidateEnrichmentPrepareView,
    CandidateEnrichmentFollowUpView,
    CandidateWebsiteEnrichmentView,
    DiscoveryCandidateReviewView,
    ChannelPackageManualExportView,
    FourChannelManualExportView,
    CompanyFactVerifyView,
    DiscoveryProfileView,
    DiscoveryRunView,
    FollowUpView,
    GoogleMapsDiscoveryConfigView,
    GoogleMapsDiscoveryRunView,
    GoogleMapsDiscoveryTestView,
    GrowthWorkspaceView,
    InboundRfqView,
    LeadVisitView,
    MetricReceiptCreateView,
    MarketWatchCreateView,
    MarketWatchView,
    ManualOpportunityImportView,
    OutreachDraftView,
    OpportunityReviewView,
    CRMHandoffView,
    PublishBatchCreateView,
    PublishBatchDetailView,
    PublishBatchRetryFailedView,
    PromotionPlanApproveView,
    PromotionPlanRegenerateView,
    ReactivationApproveView,
    ReactivationCreateView,
    ReactivationDraftView,
    TradeIndicatorView,
    TradeSnapshotListView,
    TradeSyncView,
)
from .agent_views import (
    AgentRunApproveView,
    AgentRunDetailView,
    AgentRunListView,
    AgentRunStartView,
    GrowthEventAcknowledgeView,
    GrowthEventListView,
)

urlpatterns = [
    path("growth/workspace", GrowthWorkspaceView.as_view(), name="growth-workspace"),
    path("growth/markets/watch", MarketWatchCreateView.as_view(), name="growth-market-watch-create"),
    path("growth/markets/<str:country_code>/watch", MarketWatchView.as_view(), name="growth-market-watch"),
    path("growth/trade-syncs", TradeSyncView.as_view(), name="growth-trade-syncs"),
    path("growth/trade-snapshots", TradeSnapshotListView.as_view(), name="growth-trade-snapshots"),
    path("growth/trade-indicators", TradeIndicatorView.as_view(), name="growth-trade-indicators"),
    path("growth/reactivations", ReactivationCreateView.as_view(), name="growth-reactivation-create"),
    path(
        "growth/reactivations/<uuid:reactivation_id>/draft",
        ReactivationDraftView.as_view(),
        name="growth-reactivation-draft",
    ),
    path(
        "growth/reactivations/<uuid:reactivation_id>/approve",
        ReactivationApproveView.as_view(),
        name="growth-reactivation-approve",
    ),
    path("growth/discovery/run", DiscoveryRunView.as_view(), name="growth-discovery-run"),
    path(
        "growth/lead-visits",
        LeadVisitView.as_view(),
        name="growth-lead-visits",
    ),
    path(
        "growth/inbound-rfq",
        InboundRfqView.as_view(),
        name="growth-inbound-rfq",
    ),
    path(
        "growth/promotion-plan/approve",
        PromotionPlanApproveView.as_view(),
        name="growth-promotion-plan-approve",
    ),
    path(
        "growth/promotion-plan/regenerate",
        PromotionPlanRegenerateView.as_view(),
        name="growth-promotion-plan-regenerate",
    ),
    path(
        "growth/maps-discovery/config",
        GoogleMapsDiscoveryConfigView.as_view(),
        name="growth-maps-discovery-config",
    ),
    path(
        "growth/maps-discovery/run",
        GoogleMapsDiscoveryRunView.as_view(),
        name="growth-maps-discovery-run",
    ),
    path(
        "growth/maps-discovery/test",
        GoogleMapsDiscoveryTestView.as_view(),
        name="growth-maps-discovery-test",
    ),
    path("growth/discovery/candidate-imports", CandidateListImportView.as_view(), name="growth-candidate-import"),
    path(
        "growth/discovery/candidates/<uuid:candidate_id>/review",
        DiscoveryCandidateReviewView.as_view(),
        name="growth-candidate-review",
    ),
    path(
        "growth/enrichment/candidates/<uuid:candidate_id>/prepare",
        CandidateEnrichmentPrepareView.as_view(),
        name="growth-candidate-enrichment-prepare",
    ),
    path(
        "growth/enrichment/candidates/<uuid:candidate_id>/website",
        CandidateWebsiteEnrichmentView.as_view(),
        name="growth-candidate-website-enrichment",
    ),
    path(
        "growth/enrichment/candidates/<uuid:candidate_id>/follow-up",
        CandidateEnrichmentFollowUpView.as_view(),
        name="growth-candidate-enrichment-follow-up",
    ),
    path(
        "growth/discovery/profile",
        DiscoveryProfileView.as_view(),
        name="growth-discovery-profile",
    ),
    path(
        "growth/opportunity-imports/manual-url",
        ManualOpportunityImportView.as_view(),
        name="growth-manual-opportunity-import",
    ),
    path("growth/opportunities/<uuid:account_id>/follow-up", FollowUpView.as_view(), name="growth-follow-up"),
    path("growth/opportunities/<uuid:account_id>/draft", OutreachDraftView.as_view(), name="growth-draft"),
    path("growth/opportunities/<uuid:account_id>/review", OpportunityReviewView.as_view(), name="growth-opportunity-review"),
    path("growth/opportunities/<uuid:account_id>/crm-handoff", CRMHandoffView.as_view(), name="growth-crm-handoff"),
    path(
        "growth/channel-packages/from-platform-content/<uuid:content_id>",
        ChannelPackageFromPlatformContentView.as_view(),
        name="growth-channel-package-from-platform-content",
    ),
    path(
        "growth/channel-packages/approve-all",
        ChannelPackageBatchApproveView.as_view(),
        name="growth-channel-package-approve-all",
    ),
    path(
        "growth/channel-packages/<uuid:package_id>/approve",
        ChannelPackageApproveView.as_view(),
        name="growth-channel-package-approve",
    ),
    path(
        "growth/channel-packages/manual-export-all",
        FourChannelManualExportView.as_view(),
        name="growth-channel-package-manual-export-all",
    ),
    path(
        "growth/channel-packages/<uuid:package_id>/manual-export",
        ChannelPackageManualExportView.as_view(),
        name="growth-channel-package-manual-export",
    ),
    path("growth/metric-receipts", MetricReceiptCreateView.as_view(), name="growth-metric-receipts"),
    path("growth/publish-batches", PublishBatchCreateView.as_view(), name="growth-publish-batches"),
    path(
        "growth/publish-batches/<uuid:batch_id>",
        PublishBatchDetailView.as_view(),
        name="growth-publish-batch-detail",
    ),
    path(
        "growth/publish-batches/<uuid:batch_id>/retry-failed",
        PublishBatchRetryFailedView.as_view(),
        name="growth-publish-batch-retry-failed",
    ),
    path(
        "growth/company-facts/<uuid:fact_id>/verify",
        CompanyFactVerifyView.as_view(),
        name="growth-company-fact-verify",
    ),
    path("growth/agent/runs", AgentRunListView.as_view(), name="growth-agent-runs"),
    path("growth/agent/runs/start", AgentRunStartView.as_view(), name="growth-agent-run-start"),
    path(
        "growth/agent/runs/<uuid:run_id>",
        AgentRunDetailView.as_view(),
        name="growth-agent-run-detail",
    ),
    path(
        "growth/agent/runs/<uuid:run_id>/approve",
        AgentRunApproveView.as_view(),
        name="growth-agent-run-approve",
    ),
    path("growth/events", GrowthEventListView.as_view(), name="growth-events"),
    path("growth/events/acknowledge", GrowthEventAcknowledgeView.as_view(), name="growth-events-acknowledge"),
]
