# Generated by Django 5.2.17 on 2026-08-09 07:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0005_refresh_campaign_permissions'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=96)),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('template', models.TextField()),
                ('output_schema', models.JSONField()),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_prompt_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['purpose', '-version', 'id'],
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_attempt', models.PositiveSmallIntegerField()),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('input_snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=16)),
                ('output_json', models.JSONField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('provider_metadata', models.JSONField(default=dict)),
                ('error', models.JSONField(blank=True, null=True)),
                ('human_correction', models.JSONField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_runs', to='jobs.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_runs', to='identity.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_ai_runs', to=settings.AUTH_USER_MODEL)),
                ('prompt_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_runs', to='ai.promptversion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.UniqueConstraint(fields=('purpose', 'version'), name='ai_unique_prompt_purpose_version'),
        ),
        migrations.AddConstraint(
            model_name='airun',
            constraint=models.UniqueConstraint(fields=('job', 'job_attempt'), name='ai_unique_run_per_job_attempt'),
        ),
    ]
