# Generated by Django 5.2.17 on 2026-08-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airun',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], max_length=16),
        ),
    ]
