# Generated by Django 5.2.17 on 2026-08-12 04:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_provider_configuration'),
        ('identity', '0011_refresh_phase_b1_permissions'),
        ('jobs', '0002_add_phase_b1_job_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExecutionIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('thinking_enabled', models.BooleanField(default=False)),
                ('policy_code', models.CharField(max_length=64)),
                ('policy_version', models.PositiveIntegerField()),
                ('override_reason', models.CharField(blank=True, max_length=96)),
                ('max_output_tokens', models.PositiveIntegerField()),
                ('timeout_seconds', models.PositiveSmallIntegerField()),
                ('estimated_input_tokens', models.PositiveIntegerField()),
                ('reserved_cost_usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_ai_execution_intents', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ai_execution_intent', to='jobs.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_execution_intents', to='identity.organization')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('reserved_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('actual_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_usage_days', to='identity.organization')),
            ],
            options={
                'ordering': ['-usage_date', 'organization_id'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='RESERVED', max_length=16)),
                ('reserved_usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('actual_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_hit_tokens', models.PositiveIntegerField(default=0)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_attempts', to='ai.aiexecutionintent')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usage_attempt', to='ai.airun')),
                ('usage_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='ai.aiusageday')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='aiexecutionintent',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_cost_usd__gte', 0)), name='ai_intent_reserved_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='aiusageday',
            constraint=models.UniqueConstraint(fields=('organization', 'usage_date'), name='ai_unique_usage_day'),
        ),
        migrations.AddConstraint(
            model_name='aiusageday',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_usd__gte', 0)), name='ai_usage_day_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='aiusageday',
            constraint=models.CheckConstraint(condition=models.Q(('actual_usd__gte', 0)), name='ai_usage_day_actual_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='aiusageattempt',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_usd__gte', 0)), name='ai_usage_attempt_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='aiusageattempt',
            constraint=models.CheckConstraint(condition=models.Q(('actual_usd__gte', 0)), name='ai_usage_attempt_actual_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='aiusageattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reconciled_at__isnull', True), ('status', 'RESERVED')), models.Q(('reconciled_at__isnull', False), ('status__in', ['SUCCEEDED', 'FAILED', 'CANCELED'])), _connector='OR'), name='ai_usage_attempt_reconcile_state'),
        ),
    ]
