# Generated by Django 5.2.17 on 2026-08-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_execution_intent_and_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusageattempt',
            name='pricing_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='aiusageattempt',
            name='pricing_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
