# Generated by Django 5.2.17 on 2026-08-08 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=128)),
                ('object_id', models.UUIDField()),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit for review'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('DEPRECATE', 'Deprecate')], max_length=16)),
                ('status', models.CharField(max_length=32)),
                ('object_version', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_records', to='identity.organization')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_approval_object_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=128)),
                ('object_id', models.UUIDField()),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit for review'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('DEPRECATE', 'Deprecate')], max_length=16)),
                ('status', models.CharField(max_length=32)),
                ('object_version', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('before_metadata', models.JSONField(default=dict)),
                ('after_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='identity.organization')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_log_object_idx')],
            },
        ),
    ]
