# Generated by Django 5.2.17 on 2026-08-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrecord',
            name='action',
            field=models.CharField(choices=[('SUBMIT', 'Submit for review'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('DEPRECATE', 'Deprecate'), ('ARCHIVE', 'Archive')], max_length=16),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SUBMIT', 'Submit for review'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('DEPRECATE', 'Deprecate'), ('ARCHIVE', 'Archive')], max_length=16),
        ),
    ]
