# Generated by Django 5.2.17 on 2026-08-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_approvalrecord_action_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrecord',
            name='action',
            field=models.CharField(choices=[('SUBMIT', 'Submit for review'), ('APPROVE', 'Approve'), ('AUTO_APPROVE', 'Auto approve'), ('REJECT', 'Reject'), ('DEPRECATE', 'Deprecate'), ('ARCHIVE', 'Archive')], max_length=16),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SUBMIT', 'Submit for review'), ('APPROVE', 'Approve'), ('AUTO_APPROVE', 'Auto approve'), ('REJECT', 'Reject'), ('DEPRECATE', 'Deprecate'), ('ARCHIVE', 'Archive')], max_length=16),
        ),
    ]
