# Generated by Django 5.2.17 on 2026-08-08 16:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('PRODUCT_DOCUMENT', 'Product document'), ('PUBLIC_SOURCE', 'Public source'), ('HUMAN_ENTRY', 'Human entry'), ('STANDARD_REFERENCE', 'Standard reference')], max_length=32)),
                ('source_object_type', models.CharField(blank=True, max_length=128)),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DEPRECATED', 'Deprecated')], default='SUGGESTED', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('suggested_by_ai_run_id', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_knowledge_evidence', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_evidence', to='identity.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_knowledge_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeConcept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('SYSTEM', 'System'), ('ORGANIZATION', 'Organization')], max_length=16)),
                ('concept_type', models.CharField(choices=[('PRODUCT_TYPE', 'Product type'), ('PARAMETER', 'Parameter'), ('MATERIAL', 'Material'), ('PROCESS', 'Process'), ('STANDARD', 'Standard'), ('APPLICATION', 'Application'), ('INDUSTRY', 'Industry'), ('CUSTOMER_TYPE', 'Customer type'), ('PURCHASE_INTENT', 'Purchase intent')], max_length=32)),
                ('code', models.CharField(max_length=96)),
                ('label_zh', models.CharField(max_length=255)),
                ('label_en', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DEPRECATED', 'Deprecated')], default='SUGGESTED', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('suggested_by_ai_run_id', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_knowledge_concepts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_concepts', to='identity.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_knowledge_concepts', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ManyToManyField(blank=True, related_name='concepts', to='knowledge.knowledgeevidence')),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicate', models.CharField(choices=[('IS_A', 'Is a'), ('APPLIES_TO', 'Applies to'), ('USES_MATERIAL', 'Uses material'), ('REQUIRES_PROCESS', 'Requires process'), ('COMPLIES_WITH', 'Complies with'), ('RELEVANT_TO_CUSTOMER_TYPE', 'Relevant to customer type'), ('INDICATES_PURCHASE_INTENT', 'Indicates purchase intent'), ('REQUIRES_PARAMETER', 'Requires parameter')], max_length=40)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DEPRECATED', 'Deprecated')], default='SUGGESTED', max_length=16)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('version', models.PositiveIntegerField(default=1)),
                ('suggested_by_ai_run_id', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_knowledge_relations', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ManyToManyField(blank=True, related_name='relations', to='knowledge.knowledgeevidence')),
                ('object_concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relations', to='knowledge.knowledgeconcept')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_relations', to='identity.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_knowledge_relations', to=settings.AUTH_USER_MODEL)),
                ('subject_concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relations', to='knowledge.knowledgeconcept')),
            ],
            options={
                'ordering': ['subject_concept__code', 'predicate', 'object_concept__code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=16)),
                ('alias', models.CharField(max_length=255)),
                ('normalized_alias', models.CharField(editable=False, max_length=255)),
                ('alias_type', models.CharField(choices=[('SYNONYM', 'Synonym'), ('ABBREVIATION', 'Abbreviation'), ('MARKET_TERM', 'Market term')], default='SYNONYM', max_length=16)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DEPRECATED', 'Deprecated')], default='SUGGESTED', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('suggested_by_ai_run_id', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_knowledge_aliases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_aliases', to='identity.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_knowledge_aliases', to=settings.AUTH_USER_MODEL)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='knowledge.knowledgeconcept')),
            ],
            options={
                'ordering': ['normalized_alias', 'concept__code', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('organization__isnull', True), ('status', 'APPROVED')), fields=('language', 'normalized_alias'), name='knowledge_unique_system_approved_alias'), models.UniqueConstraint(condition=models.Q(('organization__isnull', False), ('status', 'APPROVED')), fields=('organization', 'language', 'normalized_alias'), name='knowledge_unique_org_approved_alias')],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgeconcept',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('scope', 'SYSTEM')), models.Q(('organization__isnull', False), ('scope', 'ORGANIZATION')), _connector='OR'), name='knowledge_concept_scope_organization'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeconcept',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'SYSTEM')), fields=('concept_type', 'code'), name='knowledge_unique_system_concept_code'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeconcept',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'ORGANIZATION')), fields=('organization', 'concept_type', 'code'), name='knowledge_unique_org_concept_code'),
        ),
        migrations.AddConstraint(
            model_name='knowledgerelation',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('subject_concept', 'predicate', 'object_concept'), name='knowledge_unique_system_relation'),
        ),
        migrations.AddConstraint(
            model_name='knowledgerelation',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'subject_concept', 'predicate', 'object_concept'), name='knowledge_unique_org_relation'),
        ),
        migrations.AddConstraint(
            model_name='knowledgerelation',
            constraint=models.CheckConstraint(condition=models.Q(('subject_concept', models.F('object_concept')), _negated=True), name='knowledge_relation_not_self'),
        ),
    ]
