# Generated by Django 5.2.17 on 2026-08-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledgegraphlock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgeconcept',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'ordering': ['code', 'id']},
        ),
        migrations.AlterModelOptions(
            name='knowledgeevidence',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='knowledgerelation',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'ordering': ['subject_concept__code', 'predicate', 'object_concept__code', 'id']},
        ),
        migrations.SeparateDatabaseAndState(
            # 0001 already created these auto-through tables. Only teach Django's
            # state about the explicit guarded models; the physical schema stays put.
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='KnowledgeConceptEvidence',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('knowledgeconcept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledgeconcept')),
                        ('knowledgeevidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledgeevidence')),
                    ],
                    options={
                        'db_table': 'knowledge_knowledgeconcept_evidence',
                        'base_manager_name': 'objects',
                        'default_manager_name': 'objects',
                        'unique_together': {('knowledgeconcept', 'knowledgeevidence')},
                    },
                ),
                migrations.AlterField(
                    model_name='knowledgeconcept',
                    name='evidence',
                    field=models.ManyToManyField(blank=True, related_name='concepts', through='knowledge.KnowledgeConceptEvidence', through_fields=('knowledgeconcept', 'knowledgeevidence'), to='knowledge.knowledgeevidence'),
                ),
                migrations.CreateModel(
                    name='KnowledgeRelationEvidence',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('knowledgeevidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledgeevidence')),
                        ('knowledgerelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledgerelation')),
                    ],
                    options={
                        'db_table': 'knowledge_knowledgerelation_evidence',
                        'base_manager_name': 'objects',
                        'default_manager_name': 'objects',
                        'unique_together': {('knowledgerelation', 'knowledgeevidence')},
                    },
                ),
                migrations.AlterField(
                    model_name='knowledgerelation',
                    name='evidence',
                    field=models.ManyToManyField(blank=True, related_name='relations', through='knowledge.KnowledgeRelationEvidence', through_fields=('knowledgerelation', 'knowledgeevidence'), to='knowledge.knowledgeevidence'),
                ),
            ],
        ),
    ]
