# Generated by Django 5.2.17 on 2026-08-21 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_refresh_mission_permissions'),
        ('knowledge', '0003_alter_knowledgeconcept_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeevidence',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgeevidence',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgeevidence',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgeevidence',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgeevidence',
            name='sensitivity',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret')], default='NORMAL', max_length=16),
        ),
        migrations.AddField(
            model_name='knowledgeevidence',
            name='usage_rights',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('INTERNAL_ONLY', 'Internal only'), ('PUBLIC', 'Public use allowed')], default='UNKNOWN', max_length=24),
        ),
        migrations.CreateModel(
            name='CompanyFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=96)),
                ('key', models.CharField(max_length=160)),
                ('value_json', models.JSONField()),
                ('fact_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=16)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('RESTRICTED', 'Restricted')], default='INTERNAL', max_length=16)),
                ('sensitivity', models.CharField(choices=[('NORMAL', 'Normal'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret')], default='NORMAL', max_length=16)),
                ('claim_policy', models.CharField(choices=[('ALLOW_WITH_EVIDENCE', 'Allow with evidence'), ('INTERNAL_CONTEXT_ONLY', 'Internal context only'), ('NEVER_SEND_TO_MODEL', 'Never send to model')], default='INTERNAL_CONTEXT_ONLY', max_length=32)),
                ('risk_level', models.CharField(choices=[('STANDARD', 'Standard'), ('HIGH', 'High')], default='STANDARD', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_company_facts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_facts', to='identity.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_company_facts', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_facts', to='knowledge.companyfact')),
            ],
            options={
                'ordering': ['profile_id', 'namespace', 'key', '-version'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFactEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('support_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SUPPORTING', 'Supporting'), ('CONTRADICTING', 'Contradicting')], max_length=16)),
                ('citation_label', models.CharField(blank=True, max_length=255)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('bound_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bound_company_fact_evidence', to=settings.AUTH_USER_MODEL)),
                ('company_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_bindings', to='knowledge.companyfact')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_fact_bindings', to='knowledge.knowledgeevidence')),
            ],
            options={
                'ordering': ['company_fact_id', 'support_type', 'bound_at', 'id'],
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='companyfact',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='company_facts', through='knowledge.CompanyFactEvidence', to='knowledge.knowledgeevidence'),
        ),
        migrations.CreateModel(
            name='CompanyKnowledgeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=16)),
                ('brand_name', models.CharField(max_length=255)),
                ('legal_name_zh', models.CharField(blank=True, max_length=255)),
                ('legal_name_en', models.CharField(blank=True, max_length=255)),
                ('brand_aliases', models.JSONField(blank=True, default=list)),
                ('internal_summary', models.TextField(blank=True)),
                ('default_language', models.CharField(default='en', max_length=16)),
                ('supported_languages', models.JSONField(blank=True, default=list)),
                ('primary_site_origin', models.URLField(blank=True, max_length=2048)),
                ('disclosure_rules', models.JSONField(blank=True, default=dict)),
                ('prohibited_claims', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_company_knowledge_profiles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_knowledge_profiles', to='identity.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_company_knowledge_profiles', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_profiles', to='knowledge.companyknowledgeprofile')),
            ],
            options={
                'ordering': ['organization_id', '-version'],
            },
        ),
        migrations.AddField(
            model_name='companyfact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='knowledge.companyknowledgeprofile'),
        ),
        migrations.AddConstraint(
            model_name='companyfactevidence',
            constraint=models.UniqueConstraint(fields=('company_fact', 'evidence', 'support_type'), name='knowledge_unique_company_fact_evidence'),
        ),
        migrations.AddConstraint(
            model_name='companyknowledgeprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'version'), name='knowledge_unique_company_profile_version'),
        ),
        migrations.AddConstraint(
            model_name='companyknowledgeprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APPROVED')), fields=('organization',), name='knowledge_one_approved_company_profile'),
        ),
        migrations.AddConstraint(
            model_name='companyfact',
            constraint=models.UniqueConstraint(fields=('profile', 'namespace', 'key', 'version'), name='knowledge_unique_company_fact_version'),
        ),
        migrations.AddConstraint(
            model_name='companyfact',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'VERIFIED')), fields=('profile', 'namespace', 'key'), name='knowledge_one_verified_company_fact'),
        ),
        migrations.AddConstraint(
            model_name='companyfact',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='knowledge_company_fact_valid_dates'),
        ),
    ]
