# Generated by Django 5.2.17 on 2026-08-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_knowledgeconcept_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeconcept',
            name='concept_type',
            field=models.CharField(choices=[('PRODUCT_TYPE', 'Product type'), ('PARAMETER', 'Parameter'), ('MATERIAL', 'Material'), ('PROCESS', 'Process'), ('STANDARD', 'Standard'), ('APPLICATION', 'Application'), ('INDUSTRY', 'Industry'), ('CUSTOMER_TYPE', 'Customer type'), ('PURCHASE_INTENT', 'Purchase intent'), ('CAPABILITY', 'Capability'), ('REQUIREMENT', 'Requirement')], max_length=32),
        ),
        migrations.AlterField(
            model_name='knowledgerelation',
            name='predicate',
            field=models.CharField(choices=[('IS_A', 'Is a'), ('APPLIES_TO', 'Applies to'), ('USES_MATERIAL', 'Uses material'), ('REQUIRES_PROCESS', 'Requires process'), ('COMPLIES_WITH', 'Complies with'), ('RELEVANT_TO_CUSTOMER_TYPE', 'Relevant to customer type'), ('INDICATES_PURCHASE_INTENT', 'Indicates purchase intent'), ('REQUIRES_PARAMETER', 'Requires parameter'), ('SATISFIES', 'Satisfies'), ('HAS_REQUIREMENT', 'Has requirement')], max_length=40),
        ),
    ]
