# Generated by Django 5.2.17 on 2026-08-21 11:50

import apps.knowledge.context_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_concepts'),
        ('identity', '0015_refresh_mission_permissions'),
        ('knowledge', '0004_company_fact_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICPProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=96)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_industries', models.JSONField(default=list, validators=[apps.knowledge.context_models.validate_context_string_list])),
                ('company_types', models.JSONField(default=list, validators=[apps.knowledge.context_models.validate_context_string_list])),
                ('buyer_roles', models.JSONField(default=list, validators=[apps.knowledge.context_models.validate_context_string_list])),
                ('target_markets', models.JSONField(default=list, validators=[apps.knowledge.context_models.validate_context_string_list])),
                ('languages', models.JSONField(default=list, validators=[apps.knowledge.context_models.validate_context_string_list])),
                ('pain_points', models.JSONField(default=list, validators=[apps.knowledge.context_models.validate_context_string_list])),
                ('buying_triggers', models.JSONField(default=list, validators=[apps.knowledge.context_models.validate_context_string_list])),
                ('exclusion_rules', models.JSONField(default=list, validators=[apps.knowledge.context_models.validate_context_string_list])),
                ('preferred_channels', models.JSONField(default=list, validators=[apps.knowledge.context_models.validate_context_string_list])),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_icp_profiles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='icp_profiles', to='identity.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_icp_profiles', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_icp_profiles', to='knowledge.icpprofile')),
            ],
            options={
                'ordering': ['organization_id', 'code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ICPProductLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], max_length=16)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('use_cases', models.JSONField(default=list, validators=[apps.knowledge.context_models.validate_context_string_list])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='icp_links', to='catalog.product')),
                ('icp_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='knowledge.icpprofile')),
            ],
            options={
                'ordering': ['icp_profile_id', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_url', models.URLField(max_length=2048)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=16)),
                ('page_type', models.CharField(choices=[('HOME', 'Home'), ('PRODUCT', 'Product'), ('INDUSTRY', 'Industry'), ('APPLICATION', 'Application'), ('CAPABILITY', 'Capability'), ('CASE_STUDY', 'Case study'), ('ABOUT', 'About'), ('CONTACT', 'Contact'), ('RFQ', 'RFQ'), ('OTHER', 'Other')], max_length=24)),
                ('language', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=500)),
                ('content_summary', models.TextField(blank=True)),
                ('primary_cta_label', models.CharField(blank=True, max_length=255)),
                ('primary_cta_url', models.URLField(blank=True, max_length=2048)),
                ('seo_keywords', models.JSONField(default=list, validators=[apps.knowledge.context_models.validate_context_string_list])),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('SIGNED_FEED', 'Signed feed'), ('CRAWL', 'Crawl')], max_length=16)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_website_pages', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='website_pages', to='identity.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_website_pages', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_website_pages', to='knowledge.websitepage')),
            ],
            options={
                'ordering': ['organization_id', 'canonical_url', '-version'],
            },
        ),
        migrations.CreateModel(
            name='WebsitePageConceptLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('INDUSTRY', 'Industry'), ('APPLICATION', 'Application'), ('PURCHASE_INTENT', 'Purchase intent')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='website_page_links', to='knowledge.knowledgeconcept')),
                ('website_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_links', to='knowledge.websitepage')),
            ],
            options={
                'ordering': ['website_page_id', 'role', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebsitePageProductLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('RELATED', 'Related')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='website_page_links', to='catalog.product')),
                ('website_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='knowledge.websitepage')),
            ],
            options={
                'ordering': ['website_page_id', 'relation_type', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='icpprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'code', 'version'), name='knowledge_unique_icp_profile_version'),
        ),
        migrations.AddConstraint(
            model_name='icpprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APPROVED')), fields=('organization', 'code'), name='knowledge_one_approved_icp_profile'),
        ),
        migrations.AddConstraint(
            model_name='icpprofile',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='knowledge_icp_profile_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='icpproductlink',
            constraint=models.UniqueConstraint(fields=('icp_profile', 'product'), name='knowledge_unique_icp_product_link'),
        ),
        migrations.AddConstraint(
            model_name='icpproductlink',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gt', 0)), name='knowledge_icp_product_priority_positive'),
        ),
        migrations.AddConstraint(
            model_name='websitepage',
            constraint=models.UniqueConstraint(fields=('organization', 'canonical_url', 'version'), name='knowledge_unique_website_page_version'),
        ),
        migrations.AddConstraint(
            model_name='websitepage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'VERIFIED')), fields=('organization', 'canonical_url'), name='knowledge_one_verified_website_page'),
        ),
        migrations.AddConstraint(
            model_name='websitepage',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='knowledge_website_page_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='websitepageconceptlink',
            constraint=models.UniqueConstraint(fields=('website_page', 'role', 'concept'), name='knowledge_unique_page_concept_link'),
        ),
        migrations.AddConstraint(
            model_name='websitepageproductlink',
            constraint=models.UniqueConstraint(fields=('website_page', 'product'), name='knowledge_unique_page_product_link'),
        ),
    ]
