# Generated by Django 5.2.17 on 2026-08-21 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_concepts'),
        ('growth', '0048_alter_missionentitylink_entity_type'),
        ('identity', '0015_refresh_mission_permissions'),
        ('knowledge', '0005_icp_website_page_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeContextSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('MISSION', 'Mission')], default='MISSION', max_length=16)),
                ('schema_version', models.CharField(default='knowledge-context-v1', max_length=64)),
                ('builder_version', models.CharField(max_length=64)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('payload_size_bytes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_context_snapshots', to='knowledge.companyknowledgeprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_knowledge_context_snapshots', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_context_snapshots', to='growth.growthmission')),
                ('mission_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_context_snapshots', to='growth.missionplan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_context_snapshots', to='identity.organization')),
                ('primary_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_context_snapshots', to='catalog.product')),
            ],
            options={
                'ordering': ['organization_id', 'scope', 'created_at', 'id'],
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('organization', 'scope', 'source_fingerprint'), name='knowledge_unique_context_source_fingerprint'), models.CheckConstraint(condition=models.Q(('scope', 'MISSION')), name='knowledge_context_scope_mission'), models.CheckConstraint(condition=models.Q(('schema_version', 'knowledge-context-v1')), name='knowledge_context_schema_v1'), models.CheckConstraint(condition=models.Q(('source_fingerprint__regex', '^[0-9a-f]{64}$')), name='knowledge_context_source_hash_valid'), models.CheckConstraint(condition=models.Q(('payload_hash__regex', '^[0-9a-f]{64}$')), name='knowledge_context_payload_hash_valid')],
            },
        ),
    ]
