# Generated by Django 5.2.17 on 2026-08-09 00:55

import uuid
from decimal import Decimal

import apps.catalog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0003_refresh_product_permissions"),
        ("knowledge", "0002_knowledgegraphlock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_zh", models.CharField(blank=True, max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                (
                    "module_min",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))],
                    ),
                ),
                (
                    "module_max",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))],
                    ),
                ),
                (
                    "tooth_count_min",
                    models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
                ),
                (
                    "tooth_count_max",
                    models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
                ),
                (
                    "pressure_angle",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                ("accuracy_grade", models.CharField(blank=True, max_length=128)),
                ("heat_treatment", models.CharField(blank=True, max_length=255)),
                ("surface_treatment", models.CharField(blank=True, max_length=255)),
                (
                    "manufacturing_capabilities",
                    models.JSONField(default=list, validators=[apps.catalog.models.validate_string_list]),
                ),
                (
                    "inspection_capabilities",
                    models.JSONField(default=list, validators=[apps.catalog.models.validate_string_list]),
                ),
                ("moq", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("lead_time", models.CharField(blank=True, max_length=255)),
                ("landing_page_url", models.URLField(blank=True, max_length=2048)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="identity.organization"),
                ),
            ],
            options={"ordering": ["name_en", "id"]},
        ),
        migrations.CreateModel(
            name="ProductConceptLink",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TYPE", "Type"),
                            ("MATERIAL", "Material"),
                            ("PROCESS", "Process"),
                            ("STANDARD", "Standard"),
                            ("APPLICATION", "Application"),
                            ("PARAMETER", "Parameter"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_links",
                        to="knowledge.knowledgeconcept",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="identity.organization"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concept_links",
                        to="catalog.product",
                    ),
                ),
            ],
            options={"ordering": ["role", "concept__code", "id"]},
        ),
        migrations.AddField(
            model_name="product",
            name="concepts",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="catalog.ProductConceptLink",
                to="knowledge.knowledgeconcept",
            ),
        ),
        migrations.AddConstraint(
            model_name="productconceptlink",
            constraint=models.UniqueConstraint(
                fields=("product", "role", "concept"), name="catalog_unique_product_role_concept"
            ),
        ),
        migrations.AddConstraint(
            model_name="productconceptlink",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="catalog_product_link_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("module_min__gt", 0)), name="catalog_product_module_min_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("module_max__gte", models.F("module_min"))),
                name="catalog_product_module_range_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("tooth_count_min__gt", 0)), name="catalog_product_tooth_min_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("tooth_count_max__gte", models.F("tooth_count_min"))),
                name="catalog_product_tooth_range_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("pressure_angle__gt", 0), ("pressure_angle__lte", 90)),
                name="catalog_product_pressure_angle_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("moq__gt", 0)), name="catalog_product_moq_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="catalog_product_version_positive"
            ),
        ),
    ]
