# Generated by Django 5.2.17 on 2026-08-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("identity", "0003_refresh_product_permissions"),
        ("knowledge", "0002_knowledgegraphlock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["name_en", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="productconceptlink",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["role", "concept__code", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="productconceptlink",
            name="catalog_unique_product_role_concept",
        ),
        migrations.AddField(
            model_name="productconceptlink",
            name="retired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="productconceptlink",
            index=models.Index(
                fields=["product", "retired_at", "role"],
                name="catalog_link_active_role_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productconceptlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(retired_at__isnull=True),
                fields=("product", "role", "concept"),
                name="catalog_unique_product_role_concept",
            ),
        ),
    ]
