# Generated by Django 5.2.17 on 2026-08-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_concepts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productconceptlink',
            name='role',
            field=models.CharField(choices=[('TYPE', 'Type'), ('MATERIAL', 'Material'), ('PROCESS', 'Process'), ('STANDARD', 'Standard'), ('APPLICATION', 'Application'), ('PARAMETER', 'Parameter'), ('CAPABILITY', 'Capability')], max_length=16),
        ),
    ]
