import { QueryClient, VueQueryPlugin } from "@tanstack/vue-query"
import { render, screen } from "@testing-library/vue"
import userEvent from "@testing-library/user-event"
import { afterEach, expect, it, vi } from "vitest"
import AssetUnderstandingPanel from "./AssetUnderstandingPanel.vue"

afterEach(()=>vi.unstubAllGlobals())
const response=(value:unknown)=>new Response(JSON.stringify(value),{status:200,headers:{"Content-Type":"application/json"}})
const fakeStatus={mode:"FAKE_OFFLINE",provider_label:"Fake / 离线演示",model:"fake-v1",configured:false,real_requests_enabled:false}
const realStatus={mode:"CONFIGURED_AI",provider_label:"DeepSeek 官方 API",model:"deepseek-chat",configured:true,real_requests_enabled:true}
const result={job:{id:"j1",status:"SUCCEEDED",progress:100,attempt:1,max_attempts:3,error:null},provider_label:"Fake Provider · 本地演示",is_partial:false,warnings:[],facts:[{id:"f1",product:"p1",asset:"a1",category:"SPECIFICATION",field_name:"accuracy",value:"DIN 6",confidence:"0.9000",source_page:1,source_region:null,source_excerpt:"Accuracy: DIN 6",risk_level:"HIGH",review_status:"SUGGESTED",provider_label:"Fake Provider · 本地演示",is_demo:true,reviewed_by:null,reviewed_at:null,review_note:"",created_at:"2026-08-15T00:00:00Z",updated_at:"2026-08-15T00:00:00Z"}]}
function mount(productId="p1"){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});render(AssetUnderstandingPanel,{props:{assetId:"a1",productId,canManage:true},global:{plugins:[[VueQueryPlugin,{queryClient:client}]]}})}

it("requires a product before preparing facts",()=>{mount("");expect(screen.getByRole("button",{name:"准备产品事实"})).toBeDisabled()})
it("shows explicit Fake evidence and approves only after a human action",async()=>{document.cookie="csrftoken=t; path=/";const fetch=vi.fn().mockResolvedValueOnce(response(fakeStatus)).mockResolvedValueOnce(response(result)).mockResolvedValueOnce(response({...result.facts[0],review_status:"VERIFIED"}));vi.stubGlobal("fetch",fetch);mount();expect(await screen.findByText("当前为 Fake / 离线模式，资料文本不会发送给外部模型。")).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"准备产品事实"}));expect(await screen.findByText("Fake Provider · 本地演示")).toBeInTheDocument();expect(screen.getByText("Accuracy: DIN 6")).toBeInTheDocument();expect(screen.getByText("高风险事实，必须人工确认")).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"确认写入事实库"}));expect(await screen.findByText("已验证")).toBeInTheDocument();expect(screen.getByText("已进入事实库，可供 ICP 与多渠道内容使用")).toBeInTheDocument();expect(fetch).toHaveBeenCalledTimes(3)})
it("requires active consent before sending bounded PDF text to DeepSeek",async()=>{document.cookie="csrftoken=t; path=/";const realResult={...result,provider_label:"DeepSeek 官方 API",facts:result.facts.map(fact=>({...fact,is_demo:false,provider_label:"DeepSeek 官方 API"}))};const fetch=vi.fn().mockResolvedValueOnce(response(realStatus)).mockResolvedValueOnce(response(realResult));vi.stubGlobal("fetch",fetch);mount();const consent=await screen.findByRole("checkbox");const prepare=screen.getByRole("button",{name:"准备产品事实"});expect(screen.getByText(/PDF 文件本身不会上传/)).toBeInTheDocument();expect(prepare).toBeDisabled();await userEvent.click(consent);expect(prepare).toBeEnabled();await userEvent.click(prepare);expect(await screen.findByText("DeepSeek 官方 API")).toBeInTheDocument();expect(JSON.parse(fetch.mock.calls[1][1].body)).toEqual({product_id:"p1",external_text_consent:true})})
it("retries a failed parse without asking for another upload",async()=>{document.cookie="csrftoken=t; path=/";const failed={...result,job:{...result.job,status:"FAILED",error:{code:"parse_failed"}},facts:[]};const fetch=vi.fn().mockResolvedValueOnce(response(fakeStatus)).mockResolvedValueOnce(response(failed)).mockResolvedValueOnce(response(result));vi.stubGlobal("fetch",fetch);mount();await screen.findByText("当前为 Fake / 离线模式，资料文本不会发送给外部模型。");await userEvent.click(screen.getByRole("button",{name:"查看已有事实"}));await userEvent.click(await screen.findByRole("button",{name:"重试解析"}));expect(await screen.findByText("Accuracy: DIN 6")).toBeInTheDocument();expect(fetch.mock.calls[2][0]).toBe("/api/v1/assets/a1/understanding/retry")})
