import { QueryClient, VueQueryPlugin } from "@tanstack/vue-query"
import { fireEvent, render, screen } from "@testing-library/vue"
import userEvent from "@testing-library/user-event"
import { afterEach, expect, it, vi } from "vitest"
import { currentUserQueryOptions } from "../auth/auth"
import AssetLibraryPage from "./AssetLibraryPage.vue"

it("renders real assets and exposes upload only to managers", async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({next:null,previous:null,results:[{id:"a1",asset_type:"IMAGE",original_filename:"gear.jpg",mime_type:"image/jpeg",size_bytes:42,status:"READY",tags:["product"],products:[]}]}),{status:200,headers:{"Content-Type":"application/json"}})));const client=new QueryClient({defaultOptions:{queries:{retry:false}}});client.setQueryData(currentUserQueryOptions().queryKey,{user:{id:1,username:"op"},organization:{id:"o1",name:"Org",slug:"org"},membership:{id:"m",role:"OPERATOR",status:"ACTIVE",permissions:["assets.read","assets.manage"]}});render(AssetLibraryPage,{global:{plugins:[[VueQueryPlugin,{queryClient:client}]]}});expect(await screen.findByText("gear.jpg")).toBeInTheDocument();expect(screen.getByRole("button",{name:"上传素材"})).toBeInTheDocument()})

afterEach(()=>vi.unstubAllGlobals())
function renderAssets(permissions:string[],fetch:ReturnType<typeof vi.fn>){vi.stubGlobal("fetch",fetch);const client=new QueryClient({defaultOptions:{queries:{retry:false}}});client.setQueryData(currentUserQueryOptions().queryKey,{user:{id:1,username:"user"},organization:{id:"o1",name:"Org",slug:"org"},membership:{id:"m",role:"READ_ONLY",status:"ACTIVE",permissions}});render(AssetLibraryPage,{global:{plugins:[[VueQueryPlugin,{queryClient:client}]]}})}
it("hides upload and product-link controls from readers",async()=>{renderAssets(["assets.read"],vi.fn().mockResolvedValue(new Response(JSON.stringify({next:null,previous:null,results:[{id:"a1",asset_type:"IMAGE",original_filename:"reader.jpg",mime_type:"image/jpeg",size_bytes:1,status:"READY",tags:[],products:[]}]}),{status:200,headers:{"Content-Type":"application/json"}})));expect(await screen.findByText("reader.jpg")).toBeInTheDocument();expect(screen.queryByRole("button",{name:"上传素材"})).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"关联"})).not.toBeInTheDocument()})
it("rejects a javascript download URL without opening a window",async()=>{document.cookie="csrftoken=t; path=/";const open=vi.spyOn(window,"open").mockImplementation(()=>null);const fetch=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({next:null,previous:null,results:[{id:"a1",asset_type:"IMAGE",original_filename:"unsafe.jpg",mime_type:"image/jpeg",size_bytes:1,status:"READY",tags:[],products:[]}]}),{status:200,headers:{"Content-Type":"application/json"}})).mockResolvedValueOnce(new Response(JSON.stringify({url:"javascript:alert(1)",expires_in:60}),{status:200,headers:{"Content-Type":"application/json"}}));renderAssets(["assets.read"],fetch);await userEvent.click(await screen.findByRole("button",{name:"安全下载"}));expect(open).not.toHaveBeenCalled();expect(screen.getByRole("status")).toHaveTextContent("下载地址不安全")})
it("shows a named retry for a 503 asset list",async()=>{renderAssets(["assets.read"],vi.fn().mockResolvedValue(new Response(null,{status:503})));expect(await screen.findByRole("alert")).toHaveTextContent("素材没有加载成功");expect(screen.getByRole("button",{name:"重新加载素材"})).toBeInTheDocument()})
it("maps an upload field error and focuses the file control",async()=>{document.cookie="csrftoken=t; path=/";const fetch=vi.fn((path:string,init?:RequestInit)=>Promise.resolve(init?.method==="POST"?new Response(JSON.stringify({errors:{file:["文件内容不受支持。"]}}),{status:400,headers:{"Content-Type":"application/json"}}):new Response(JSON.stringify({next:null,previous:null,results:[]}),{status:200,headers:{"Content-Type":"application/json"}})));renderAssets(["assets.read","assets.manage"],fetch);await userEvent.click(await screen.findByRole("button",{name:"上传素材"}));const fileInput=screen.getByLabelText("文件");expect(screen.getByRole("heading",{name:"上传素材"})).toHaveFocus();await userEvent.upload(fileInput,new File(["bad"],"bad.bin"));await fireEvent.submit(fileInput.closest("form")!);expect(await screen.findByRole("alert")).toHaveTextContent("文件内容不受支持");expect(fileInput).toHaveFocus()})
