# Generated by Django 5.2.17 on 2026-08-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('CONTENT_GENERATE', 'Content generate'), ('ASSET_UNDERSTAND', 'Asset understand')], max_length=32),
        ),
    ]
