# Generated by Django 5.2.17 on 2026-08-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
