# Generated by Django 5.2.17 on 2026-08-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_heartbeat_at_job_lease_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('CONTENT_GENERATE', 'Content generate'), ('CONTENT_RECOMMEND', 'Content recommend'), ('ASSET_UNDERSTAND', 'Asset understand'), ('CONTENT_PLATFORM_VARIANTS', 'Content platform variants')], max_length=32),
        ),
    ]
