# Generated by Django 5.2.17 on 2026-08-10 08:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0002_add_airun_canceled_status'),
        ('identity', '0011_refresh_phase_b1_permissions'),
        ('knowledge', '0004_capability_requirement_types'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_domain', models.CharField(blank=True, max_length=253)),
                ('country_hint', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('ANALYZING', 'Analyzing'), ('ANALYZED', 'Analyzed'), ('REVIEWED', 'Reviewed'), ('READY_FOR_HANDOFF', 'Ready for handoff'), ('HANDED_OFF', 'Handed off'), ('DISMISSED', 'Dismissed')], default='DISCOVERED', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_lead_candidates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('source_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_candidates', to='sources.sourcesignal')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadCandidateEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='leads.leadcandidate')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_links', to='sources.sourceevidence')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('source_signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_evidence_links', to='sources.sourcesignal')),
            ],
            options={
                'ordering': ['candidate_id', 'insight_id', 'created_at', 'id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='leadcandidate',
            name='evidence',
            field=models.ManyToManyField(related_name='lead_candidates', through='leads.LeadCandidateEvidence', through_fields=('candidate', 'evidence'), to='sources.sourceevidence'),
        ),
        migrations.CreateModel(
            name='LeadInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('intent_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)])),
                ('company_fit_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(25)])),
                ('specificity_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('capability_fit_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('recency_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('score_band', models.CharField(choices=[('HIGH', 'High'), ('WATCH', 'Watch'), ('OBSERVE', 'Observe'), ('LOW', 'Low')], max_length=16)),
                ('high_value_eligible', models.BooleanField(default=False)),
                ('traceable_source', models.BooleanField(default=False)),
                ('explicit_need_or_company_match', models.BooleanField(default=False)),
                ('capability_evidence', models.BooleanField(default=False)),
                ('audited_run', models.BooleanField(default=False)),
                ('ontology_snapshot_complete', models.BooleanField(default=False)),
                ('explanation', models.JSONField(default=dict)),
                ('extracted_requirement_values', models.JSONField(default=list)),
                ('evidence_confidence', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('company_match_confidence', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('ai_confidence', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('ontology_snapshot', models.JSONField()),
                ('ai_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_insights', to='ai.airun')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insights', to='leads.leadcandidate')),
                ('evidence', models.ManyToManyField(related_name='lead_insights', through='leads.LeadCandidateEvidence', through_fields=('insight', 'evidence'), to='sources.sourceevidence')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
            ],
            options={
                'ordering': ['candidate_id', 'version', 'id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='leadcandidateevidence',
            name='insight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='leads.leadinsight'),
        ),
        migrations.AddField(
            model_name='leadcandidate',
            name='latest_insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_for_candidates', to='leads.leadinsight'),
        ),
        migrations.CreateModel(
            name='LeadInsightRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extracted_value', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('capability_concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_capability_links', to='knowledge.knowledgeconcept')),
                ('capability_knowledge_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_capability_evidence_links', to='knowledge.knowledgeevidence')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='leads.leadinsight')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('requirement_concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_requirement_links', to='knowledge.knowledgeconcept')),
                ('source_evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_requirement_links', to='sources.sourceevidence')),
            ],
            options={
                'ordering': ['insight_id', 'created_at', 'id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='leadinsight',
            constraint=models.UniqueConstraint(fields=('candidate', 'version'), name='leads_unique_insight_version'),
        ),
        migrations.AddConstraint(
            model_name='leadinsight',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='leads_insight_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='leadcandidateevidence',
            constraint=models.UniqueConstraint(fields=('insight', 'evidence'), name='leads_unique_insight_evidence'),
        ),
        migrations.AddConstraint(
            model_name='leadcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='leads_candidate_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='leadinsightrequirement',
            constraint=models.UniqueConstraint(fields=('insight', 'requirement_concept', 'source_evidence', 'extracted_value', 'unit'), name='leads_unique_insight_requirement'),
        ),
    ]
