# Generated by Django 5.2.17 on 2026-08-10 08:58

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_add_airun_canceled_status'),
        ('identity', '0011_refresh_phase_b1_permissions'),
        ('leads', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leadinsight',
            constraint=models.UniqueConstraint(fields=('ai_run',), name='leads_unique_insight_ai_run'),
        ),
        migrations.AddConstraint(
            model_name='leadinsight',
            constraint=models.CheckConstraint(condition=models.Q(('capability_fit_score__gte', 0), ('capability_fit_score__lte', 15), ('company_fit_score__gte', 0), ('company_fit_score__lte', 25), ('intent_score__gte', 0), ('intent_score__lte', 30), ('recency_score__gte', 0), ('recency_score__lte', 10), ('score__gte', 0), ('score__lte', 100), ('specificity_score__gte', 0), ('specificity_score__lte', 20)), name='leads_insight_scores_bounded'),
        ),
        migrations.AddConstraint(
            model_name='leadinsight',
            constraint=models.CheckConstraint(condition=models.Q(('score', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('intent_score'), '+', models.F('company_fit_score')), '+', models.F('specificity_score')), '+', models.F('capability_fit_score')), '+', models.F('recency_score')))), name='leads_insight_score_sum'),
        ),
        migrations.AddConstraint(
            model_name='leadinsight',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('score__gte', 80), ('score_band', 'HIGH')), models.Q(('score__gte', 60), ('score__lt', 80), ('score_band', 'WATCH')), models.Q(('score__gte', 40), ('score__lt', 60), ('score_band', 'OBSERVE')), models.Q(('score__lt', 40), ('score_band', 'LOW')), _connector='OR'), name='leads_insight_band_matches_score'),
        ),
        migrations.AddConstraint(
            model_name='leadinsight',
            constraint=models.CheckConstraint(condition=models.Q(('high_value_eligible', False), models.Q(('audited_run', True), ('capability_evidence', True), ('explicit_need_or_company_match', True), ('high_value_eligible', True), ('ontology_snapshot_complete', True), ('score_band', 'HIGH'), ('traceable_source', True)), _connector='OR'), name='leads_insight_high_value_gated'),
        ),
        migrations.AddConstraint(
            model_name='leadinsight',
            constraint=models.CheckConstraint(condition=models.Q(('ai_confidence__gte', 0), ('ai_confidence__lte', 1), ('company_match_confidence__gte', 0), ('company_match_confidence__lte', 1), ('evidence_confidence__gte', 0), ('evidence_confidence__lte', 1)), name='leads_insight_confidence_bounded'),
        ),
    ]
