# Generated by Django 5.2.17 on 2026-08-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_add_airun_canceled_status'),
        ('identity', '0011_refresh_phase_b1_permissions'),
        ('leads', '0002_leadinsight_leads_unique_insight_ai_run_and_more'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leadinsight',
            name='leads_insight_high_value_gated',
        ),
        migrations.AddConstraint(
            model_name='leadinsight',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('audited_run', True), ('capability_evidence', True), ('explicit_need_or_company_match', True), ('high_value_eligible', True), ('ontology_snapshot_complete', True), ('score_band', 'HIGH'), ('traceable_source', True)), models.Q(('high_value_eligible', False), models.Q(('audited_run', True), ('capability_evidence', True), ('explicit_need_or_company_match', True), ('ontology_snapshot_complete', True), ('score_band', 'HIGH'), ('traceable_source', True), _negated=True)), _connector='OR'), name='leads_insight_high_value_gated'),
        ),
    ]
