# Generated by Django 5.2.17 on 2026-08-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_leadinsight_leads_insight_high_value_gated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcandidate',
            name='analysis_lease_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
