# Generated by Django 5.2.17 on 2026-08-10 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_refresh_phase_b1_permissions'),
        ('leads', '0004_leadcandidate_analysis_lease_token'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadcandidate',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'ordering': ['-created_at', '-id']},
        ),
        migrations.AddConstraint(
            model_name='leadcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('analysis_lease_token__isnull', True), ('status__in', ['ANALYZING', 'ANALYZED']), _connector='OR'), name='leads_candidate_lease_status_valid'),
        ),
    ]
