# Generated by Django 5.2.17 on 2026-08-10 11:18

from django.conf import settings
from django.db import migrations, models


def repair_analysis_lease_state(apps, schema_editor):
    candidate = apps.get_model("leads", "LeadCandidate")
    rows = candidate._base_manager.using(schema_editor.connection.alias)
    rows.filter(
        status="ANALYZING",
        analysis_lease_token__isnull=True,
    ).update(status="DISCOVERED")
    rows.exclude(status="ANALYZING").filter(
        analysis_lease_token__isnull=False,
    ).update(status="ANALYZING")


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_refresh_phase_b1_permissions'),
        ('leads', '0005_alter_leadcandidate_options_and_more'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leadcandidate',
            name='leads_candidate_lease_status_valid',
        ),
        migrations.RunPython(
            repair_analysis_lease_state,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='leadcandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('analysis_lease_token__isnull', False), ('status', 'ANALYZING')), models.Q(models.Q(('status', 'ANALYZING'), _negated=True), ('analysis_lease_token__isnull', True)), _connector='OR'), name='leads_candidate_lease_status_valid'),
        ),
    ]
