# Generated by Django 5.2.17 on 2026-08-10 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_add_airun_canceled_status'),
        ('identity', '0011_refresh_phase_b1_permissions'),
        ('jobs', '0002_add_phase_b1_job_types'),
        ('leads', '0006_remove_leadcandidate_leads_candidate_lease_status_valid_and_more'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAnalysisBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='LeadReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CONFIRM', 'Confirm'), ('CORRECT', 'Correct'), ('DISMISS', 'Dismiss'), ('REOPEN', 'Reopen'), ('REQUEST_MORE_EVIDENCE', 'Request more evidence')], max_length=32)),
                ('reason', models.TextField()),
                ('correction', models.JSONField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('intent_hash', models.CharField(max_length=64)),
                ('ignore_fingerprint', models.CharField(blank=True, max_length=64)),
                ('candidate_status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('ANALYZING', 'Analyzing'), ('ANALYZED', 'Analyzed'), ('REVIEWED', 'Reviewed'), ('READY_FOR_HANDOFF', 'Ready for handoff'), ('HANDED_OFF', 'Handed off'), ('DISMISSED', 'Dismissed')], max_length=24)),
                ('candidate_version', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['candidate_id', 'created_at', 'id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.RemoveConstraint(
            model_name='leadinsight',
            name='leads_unique_insight_ai_run',
        ),
        migrations.AddField(
            model_name='leadinsight',
            name='human_correction',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadinsight',
            name='origin',
            field=models.CharField(choices=[('AI', 'AI'), ('HUMAN_CORRECTION', 'Human correction')], default='AI', max_length=24),
        ),
        migrations.AddField(
            model_name='leadinsight',
            name='review_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leadinsight',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadinsight',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_lead_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadinsight',
            name='source_insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='human_corrections', to='leads.leadinsight'),
        ),
        migrations.AlterField(
            model_name='leadcandidateevidence',
            name='insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='leads.leadinsight'),
        ),
        migrations.AddConstraint(
            model_name='leadcandidateevidence',
            constraint=models.UniqueConstraint(condition=models.Q(('insight__isnull', True)), fields=('candidate', 'evidence'), name='leads_unique_candidate_selected_evidence'),
        ),
        migrations.AddConstraint(
            model_name='leadinsight',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'AI')), fields=('ai_run',), name='leads_unique_ai_origin_insight_run'),
        ),
        migrations.AddField(
            model_name='leadanalysisbinding',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_bindings', to='leads.leadcandidate'),
        ),
        migrations.AddField(
            model_name='leadanalysisbinding',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lead_analysis_binding', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='leadanalysisbinding',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization'),
        ),
        migrations.AddField(
            model_name='leadanalysisbinding',
            name='prompt_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_analysis_bindings', to='ai.promptversion'),
        ),
        migrations.AddField(
            model_name='leadanalysisbinding',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_lead_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadreview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='leads.leadcandidate'),
        ),
        migrations.AddField(
            model_name='leadreview',
            name='insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='leads.leadinsight'),
        ),
        migrations.AddField(
            model_name='leadreview',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization'),
        ),
        migrations.AddField(
            model_name='leadreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='leadreview',
            constraint=models.UniqueConstraint(fields=('organization', 'reviewer', 'idempotency_key'), name='leads_unique_review_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='leadreview',
            constraint=models.CheckConstraint(condition=models.Q(('candidate_version__gte', 1)), name='leads_review_candidate_version_positive'),
        ),
    ]
