import { QueryClient, VueQueryPlugin } from "@tanstack/vue-query"
import { render, screen } from "@testing-library/vue"
import { config } from "@vue/test-utils"
import userEvent from "@testing-library/user-event"
import { afterAll, afterEach, beforeAll, expect, it, vi } from "vitest"
import { createTestRouter } from "../../test/testRouter"
import { currentUserQueryOptions } from "../auth/auth"
import PlatformAccountsPage from "./PlatformAccountsPage.vue"

const testRouter = createTestRouter()
beforeAll(async () => {
  config.global.plugins.push(testRouter)
  await testRouter.push("/")
  await testRouter.isReady()
})
afterAll(() => {
  config.global.plugins = config.global.plugins.filter((plugin) => plugin !== testRouter)
})

it("shows safe connection summaries and manager actions",async()=>{vi.stubGlobal("fetch",vi.fn((path:string)=>Promise.resolve(new Response(JSON.stringify(path==="/api/v1/platforms"?{results:[{id:"p1",code:"linkedin",name:"LinkedIn",capabilities:["PUBLISH"]}]}:{results:[{id:"a1",platform_id:"p1",display_name:"Global LinkedIn",publish_mode:"MANUAL",status:"ACTIVE",effective_capabilities:["PUBLISH"],credential_configured:false}]}),{status:200,headers:{"Content-Type":"application/json"}}))));const client=new QueryClient({defaultOptions:{queries:{retry:false}}});client.setQueryData(currentUserQueryOptions().queryKey,{user:{id:1,username:"admin"},organization:{id:"o1",name:"Org",slug:"org"},membership:{id:"m",role:"ADMINISTRATOR",status:"ACTIVE",permissions:["publishing.read","credentials.manage"]}});render(PlatformAccountsPage,{global:{plugins:[[VueQueryPlugin,{queryClient:client}]]}});expect(await screen.findByText("Global LinkedIn")).toBeInTheDocument();expect(screen.getByRole("navigation",{name:"内容与发布工作区"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"连接平台账户"})).toBeInTheDocument();expect(screen.queryByText(/secret/i)).not.toBeInTheDocument()})

afterEach(()=>vi.unstubAllGlobals())
function renderAccounts(permissions:string[],fetch:ReturnType<typeof vi.fn>){vi.stubGlobal("fetch",fetch);const client=new QueryClient({defaultOptions:{queries:{retry:false}}});client.setQueryData(currentUserQueryOptions().queryKey,{user:{id:1,username:"reader"},organization:{id:"o1",name:"Org",slug:"org"},membership:{id:"m",role:"READ_ONLY",status:"ACTIVE",permissions}});return{...render(PlatformAccountsPage,{global:{plugins:[[VueQueryPlugin,{queryClient:client}]]}}),client}}
it("lets publishing readers see summaries but hides every manager control",async()=>{const fetch=vi.fn((path:string)=>Promise.resolve(new Response(JSON.stringify(path==="/api/v1/platforms"?{results:[{id:"p",name:"LinkedIn",code:"linkedin",capabilities:[]}]}:{results:[{id:"a",platform_id:"p",display_name:"Reader account",publish_mode:"MANUAL",status:"ACTIVE",effective_capabilities:[],credential_configured:false}]}),{status:200,headers:{"Content-Type":"application/json"}})));renderAccounts(["publishing.read"],fetch);expect(await screen.findByText("Reader account")).toBeInTheDocument();expect(screen.queryByRole("button",{name:"连接平台账户"})).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"编辑账户"})).not.toBeInTheDocument();expect(fetch.mock.calls.some(call=>call[0]==="/api/v1/connector-credentials")).toBe(false)})
it("shows a named retry on a 503 account list",async()=>{const fetch=vi.fn((path:string)=>Promise.resolve(path==="/api/v1/platforms"?new Response(JSON.stringify({results:[]}),{status:200,headers:{"Content-Type":"application/json"}}):new Response(null,{status:503})));renderAccounts(["publishing.read"],fetch);expect(await screen.findByRole("alert")).toHaveTextContent("账户没有加载成功");expect(screen.getByRole("button",{name:"重新加载账户"})).toBeInTheDocument()})
it("creates API-auto connections atomically without retaining the secret in the DOM",async()=>{document.cookie="csrftoken=t; path=/";const fetch=vi.fn((path:string,init?:RequestInit)=>{let payload:unknown={results:[]};if(path==="/api/v1/platforms")payload={results:[{id:"p",name:"LinkedIn",code:"linkedin",capabilities:["PUBLISH"]}]};if(path==="/api/v1/social-accounts/connect"&&init?.method==="POST")payload={id:"a",platform_id:"p",display_name:"Auto",publish_mode:"API_AUTO",status:"ACTIVE",effective_capabilities:["PUBLISH"],credential_configured:true};return Promise.resolve(new Response(JSON.stringify(payload),{status:200,headers:{"Content-Type":"application/json"}}))});renderAccounts(["publishing.read","credentials.manage"],fetch);await userEvent.click(await screen.findByRole("button",{name:"连接平台账户"}));await userEvent.selectOptions(screen.getByLabelText("平台"),"p");await userEvent.type(screen.getByLabelText("显示名称"),"Auto");await userEvent.type(screen.getByLabelText("平台账户标识"),"external");await userEvent.selectOptions(screen.getByLabelText("发布方式"),"API_AUTO");await userEvent.type(screen.getByLabelText(/凭据引用/),"vault://private");await userEvent.click(screen.getByRole("button",{name:"保存连接"}));expect(await screen.findByRole("status")).toHaveTextContent("已连接");const connectionCall=fetch.mock.calls.find(call=>call[0]==="/api/v1/social-accounts/connect"&&call[1]?.method==="POST")!;expect(JSON.parse(connectionCall[1].body)).toMatchObject({platform:"p",secret_reference:"vault://private",publish_mode:"API_AUTO"});expect(fetch.mock.calls.some(call=>call[0]==="/api/v1/connector-credentials"&&call[1]?.method==="POST")).toBe(false);expect(screen.queryByDisplayValue("vault://private")).not.toBeInTheDocument()})

const connectionFetch=()=>vi.fn((path:string,init?:RequestInit)=>Promise.resolve(new Response(JSON.stringify(path==="/api/v1/platforms"?{results:[{id:"p",name:"LinkedIn",code:"linkedin",capabilities:["PUBLISH"]}]}:init?.method==="POST"?{id:"a",platform_id:"p",display_name:"Auto",publish_mode:"API_AUTO",status:"ACTIVE",effective_capabilities:["PUBLISH"],credential_configured:true}:{results:[]}),{status:200,headers:{"Content-Type":"application/json"}})))
async function enterSecret(value:string){await userEvent.selectOptions(screen.getByLabelText("平台"),"p");await userEvent.selectOptions(screen.getByLabelText("发布方式"),"API_AUTO");await userEvent.type(screen.getByLabelText(/凭据引用/),value)}
it("supports export mode and wipes the secret on Escape while restoring focus",async()=>{const openerFetch=connectionFetch();renderAccounts(["publishing.read","credentials.manage"],openerFetch);const opener=await screen.findByRole("button",{name:"连接平台账户"});await userEvent.click(opener);expect(screen.getByRole("option",{name:"导出发布包"})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"连接平台账户"})).toHaveFocus();await enterSecret("escape-secret");await userEvent.keyboard("{Escape}");expect(screen.queryByRole("dialog")).not.toBeInTheDocument();expect(opener).toHaveFocus();await userEvent.click(opener);expect(screen.queryByDisplayValue("escape-secret")).not.toBeInTheDocument()})
it("wipes the secret on backdrop close",async()=>{renderAccounts(["publishing.read","credentials.manage"],connectionFetch());const opener=await screen.findByRole("button",{name:"连接平台账户"});await userEvent.click(opener);await enterSecret("backdrop-secret");await userEvent.click(screen.getByTestId("operation-modal-backdrop"));await userEvent.click(opener);expect(screen.queryByDisplayValue("backdrop-secret")).not.toBeInTheDocument()})
it("wipes secrets after a failed atomic connection and does not cache them",async()=>{document.cookie="csrftoken=t; path=/";const fetch=vi.fn((path:string,init?:RequestInit)=>Promise.resolve(new Response(JSON.stringify(path==="/api/v1/platforms"?{results:[{id:"p",name:"LinkedIn",code:"linkedin",capabilities:["PUBLISH"]}]}:init?.method==="POST"?{errors:{external_id:["Duplicate account."]}}:{results:[]}),{status:init?.method==="POST"?400:200,headers:{"Content-Type":"application/json"}})));const {client}=renderAccounts(["publishing.read","credentials.manage"],fetch);await userEvent.click(await screen.findByRole("button",{name:"连接平台账户"}));await userEvent.type(screen.getByLabelText("显示名称"),"Auto");await userEvent.type(screen.getByLabelText("平台账户标识"),"external");await enterSecret("failed-secret");await userEvent.click(screen.getByRole("button",{name:"保存连接"}));expect(await screen.findByRole("alert")).toBeInTheDocument();expect(screen.queryByDisplayValue("failed-secret")).not.toBeInTheDocument();expect(JSON.stringify(client.getQueryCache().getAll().map(query=>query.state.data))).not.toContain("failed-secret")})
