<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from "vue"
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query"
import { ApiError } from "../../api/client"
import OperationModal from "../../shared/components/OperationModal.vue"
import { currentUserQueryOptions } from "../auth/auth"
import { connectSocialAccount,listCredentials,listPlatforms,listSocialAccounts,platformAccountKeys,updateSocialAccount,type SocialAccount } from "./api"
const client=useQueryClient(),user=useQuery(currentUserQueryOptions()),open=ref(false),edit=ref<SocialAccount>(),platform=ref(""),name=ref(""),external=ref(""),mode=ref("MANUAL"),secret=ref(""),message=ref("")
const org=computed(()=>user.data.value?.organization.id??""),canManage=computed(()=>user.data.value?.membership.permissions.includes("credentials.manage")??false)
const platforms=useQuery({queryKey:computed(()=>[...platformAccountKeys.all(org.value),"platforms"]),queryFn:listPlatforms,enabled:computed(()=>Boolean(org.value))})
const accounts=useQuery({queryKey:computed(()=>platformAccountKeys.accounts(org.value)),queryFn:listSocialAccounts,enabled:computed(()=>Boolean(org.value))})
const credentials=useQuery({queryKey:computed(()=>platformAccountKeys.credentials(org.value)),queryFn:listCredentials,enabled:computed(()=>Boolean(org.value)&&canManage.value)})
const selected=computed(()=>platforms.data.value?.find(item=>item.id===platform.value))
const save=useMutation({mutationFn:()=>connectSocialAccount({platform:platform.value,external_id:external.value,display_name:name.value,publish_mode:mode.value,status:"ACTIVE",...(mode.value==="API_AUTO"?{secret_reference:secret.value}:{})}),onSuccess:async()=>{closeConnection();message.value="平台账户已连接。";await client.invalidateQueries({queryKey:platformAccountKeys.all(org.value)})},onError:()=>{secret.value=""}})
const update=useMutation({mutationFn:()=>updateSocialAccount(edit.value!.id,{display_name:name.value,publish_mode:mode.value,status:edit.value!.status}),onSuccess:async()=>{edit.value=undefined;message.value="平台账户已更新。";await client.invalidateQueries({queryKey:platformAccountKeys.all(org.value)})}})
const err=(v:unknown)=>v instanceof ApiError?v.userMessage:"连接暂时无法完成，请稍后重试。"
function openEdit(account:SocialAccount){edit.value=account;name.value=account.display_name;mode.value=account.publish_mode}
function closeConnection(){secret.value="";open.value=false}
onBeforeUnmount(()=>{secret.value=""})
</script>
<template>
  <main class="page-stack">
    <header class="workspace-head"><div><p class="eyebrow">渠道连接</p><h1>平台账户</h1><p>这里只展示安全的连接摘要，不会显示或回填密钥。</p></div><button v-if="canManage" class="primary-action" @click="open=true">连接平台账户</button></header><p v-if="message" role="status">{{ message }}</p><p v-if="accounts.isPending.value" role="status">正在加载平台账户…</p><section v-else-if="accounts.isError.value" class="panel" role="alert"><h2>账户没有加载成功</h2><p>{{ err(accounts.error.value) }}</p><button @click="accounts.refetch()">重新加载账户</button></section><section v-else-if="!accounts.data.value?.length" class="panel"><h2>还没有平台连接</h2><p>管理员可以连接手动发布账户，或配置支持自动发布的凭据。</p></section><section v-else class="cards"><article v-for="account in accounts.data.value" :key="account.id" class="panel"><div class="card-head"><h2>{{ account.display_name }}</h2><span class="pill">{{ account.status }}</span></div><p>{{ platforms.data.value?.find(p=>p.id===account.platform_id)?.name||'平台' }} · {{ account.publish_mode==='API_AUTO'?'自动发布':account.publish_mode==='EXPORT_PACKAGE'?'导出发布包':'手动发布' }}</p><p>能力：{{ account.effective_capabilities.join('、')||'只读' }}</p><p>{{ account.credential_configured?'凭据已配置':'未配置凭据' }}</p><button v-if="canManage" @click="openEdit(account)">编辑账户</button></article></section>
    <OperationModal v-if="open" title="连接平台账户" title-id="connection-title" @close="closeConnection"><form class="modal" @submit.prevent="save.mutate()"><label for="platform-account-platform">平台</label><select id="platform-account-platform" v-model="platform" required><option value="" disabled>请选择</option><option v-for="item in platforms.data.value" :key="item.id" :value="item.id">{{ item.name }}</option></select><label for="platform-account-name">显示名称</label><input id="platform-account-name" v-model="name" required><label for="platform-account-external">平台账户标识</label><input id="platform-account-external" v-model="external" required><label for="platform-account-mode">发布方式</label><select id="platform-account-mode" v-model="mode"><option value="MANUAL">手动发布</option><option value="EXPORT_PACKAGE">导出发布包</option><option value="API_AUTO" :disabled="!selected?.capabilities.includes('PUBLISH')">自动发布</option></select><template v-if="mode==='API_AUTO'"><label for="platform-account-secret">凭据引用</label><input id="platform-account-secret" v-model="secret" required type="password" autocomplete="off"><small>提交后不会再次显示。</small></template><p v-if="credentials.isError.value||save.isError.value" role="alert">{{ err(save.error.value||credentials.error.value) }}</p><div class="actions"><button type="button" @click="closeConnection">取消</button><button class="primary-action" :disabled="save.isPending.value">保存连接</button></div></form></OperationModal>
    <OperationModal v-if="edit" title="编辑平台账户" title-id="edit-title" @close="edit=undefined"><form class="modal" @submit.prevent="update.mutate()"><label>显示名称<input v-model="name" required></label><label>发布方式<select v-model="mode"><option value="MANUAL">手动发布</option><option value="EXPORT_PACKAGE">导出发布包</option><option value="API_AUTO" :disabled="!edit.credential_configured">自动发布</option></select></label><p>平台和账户标识不可更改；凭据也不会显示。</p><p v-if="update.isError.value" role="alert">{{ err(update.error.value) }}</p><div class="actions"><button type="button" @click="edit=undefined">取消</button><button class="primary-action">保存修改</button></div></form></OperationModal>
  </main>
</template>
<style scoped>.workspace-head,.card-head,.actions{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(16rem,1fr));gap:1rem}.panel{padding:1.1rem;border:1px solid var(--border-color,#d8dee8);border-radius:1rem;background:white}.pill{background:#eef3f8;padding:.25rem .6rem;border-radius:999px}.modal{display:grid;gap:1rem}.modal label{display:grid;gap:.35rem}.actions{justify-content:flex-end}@media(max-width:700px){.workspace-head{display:grid}}</style>
