# Generated by Django 5.2.17 on 2026-08-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_phaseae2eownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ai_daily_token_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
