# Generated by Django 5.2.17 on 2026-08-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_refresh_agent_lead_metrics_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='daily_publish_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
