# Generated by Django 5.2.17 on 2026-08-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_organization_daily_publish_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ai_daily_reserved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='ai_daily_reserved_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
